#!/bin/sh
#
# STImpL Test Script generated by 
# MakeTestScript on Nov 18, 2015 at 7:34:54 PM
# by the command: 
#  java sir.mts.MakeTestScript "--no-escapes" "--stimple-file" "../testplans/v0_
#  1.tsl.universe" "--script-name" "v0_1.sh" "--experiment-dir" ".." "--exe-name
#  " "../source/grep.exe" "--target" "bsh" "--print-config"

echo ">>>>>>>>running test 1"
../source/grep.exe -n I ../inputs/grep1.dat  > ../outputs/t1 2>&1

echo ">>>>>>>>running test 2"
../source/grep.exe -n 1 ../inputs/grep1.dat  > ../outputs/t2 2>&1

echo ">>>>>>>>running test 3"
../source/grep.exe -E '\?' ../inputs/grep1.dat  > ../outputs/t3 2>&1

echo ">>>>>>>>running test 4"
../source/grep.exe -G '\?' ../inputs/grep1.dat  > ../outputs/t4 2>&1

echo ">>>>>>>>running test 5"
../source/grep.exe -G '?' ../inputs/grep1.dat  > ../outputs/t5 2>&1

echo ">>>>>>>>running test 6"
../source/grep.exe -F '?' ../inputs/grep1.dat  > ../outputs/t6 2>&1

echo ">>>>>>>>running test 7"
../source/grep.exe -F '/*#include' ../inputs/grep1.dat  > ../outputs/t7 2>&1

echo ">>>>>>>>running test 8"
../source/grep.exe -G '[1-5]' ../inputs/grep1.dat  > ../outputs/t8 2>&1

echo ">>>>>>>>running test 9"
../source/grep.exe -E -c '[^a-z]' ../inputs/grep1.dat  > ../outputs/t9 2>&1

echo ">>>>>>>>running test 10"
../source/grep.exe -G '[X^YZ]' ../inputs/grep1.dat  > ../outputs/t10 2>&1

echo ">>>>>>>>running test 11"
../source/grep.exe -E '[1-]' ../inputs/grep1.dat  > ../outputs/t11 2>&1

echo ">>>>>>>>running test 12"
../source/grep.exe -G '\w' ../inputs/grep1.dat  > ../outputs/t12 2>&1

echo ">>>>>>>>running test 13"
../source/grep.exe -G '[[:alpha:]]' ../inputs/grep1.dat  > ../outputs/t13 2>&1

echo ">>>>>>>>running test 14"
../source/grep.exe -E "[[:cntrl:]]" ../inputs/grep1.dat  > ../outputs/t14 2>&1

echo ">>>>>>>>running test 15"
../source/grep.exe -E "[[:digit:]]" ../inputs/grep1.dat  > ../outputs/t15 2>&1

echo ">>>>>>>>running test 16"
../source/grep.exe -E "[[:graph:]]" ../inputs/grep1.dat  > ../outputs/t16 2>&1

echo ">>>>>>>>running test 17"
../source/grep.exe -G "[[:lower:]]" ../inputs/grep1.dat  > ../outputs/t17 2>&1

echo ">>>>>>>>running test 18"
../source/grep.exe -G "[[:print:]]" ../inputs/grep1.dat  > ../outputs/t18 2>&1

echo ">>>>>>>>running test 19"
../source/grep.exe -G '[[:punct:]]' ../inputs/grep1.dat  > ../outputs/t19 2>&1

echo ">>>>>>>>running test 20"
../source/grep.exe -G '[[:space:]]' ../inputs/grep1.dat  > ../outputs/t20 2>&1

echo ">>>>>>>>running test 21"
../source/grep.exe -G '[[:upper:]]' ../inputs/grep1.dat  > ../outputs/t21 2>&1

echo ">>>>>>>>running test 22"
../source/grep.exe -E '[[:xdigit:]]' ../inputs/grep1.dat  > ../outputs/t22 2>&1

echo ">>>>>>>>running test 23"
../source/grep.exe -E . ../inputs/grep1.dat  > ../outputs/t23 2>&1

echo ">>>>>>>>running test 24"
../source/grep.exe -E 'b$' ../inputs/grep1.dat  > ../outputs/t24 2>&1

echo ">>>>>>>>running test 25"
../source/grep.exe -E 'b\>' ../inputs/grep1.dat  > ../outputs/t25 2>&1

echo ">>>>>>>>running test 26"
../source/grep.exe -E 'b\B' ../inputs/grep1.dat  > ../outputs/t26 2>&1

echo ">>>>>>>>running test 27"
../source/grep.exe -E 'b*' ../inputs/grep1.dat  > ../outputs/t27 2>&1

echo ">>>>>>>>running test 28"
../source/grep.exe -E 'a{2,}' ../inputs/grep1.dat  > ../outputs/t28 2>&1

echo ">>>>>>>>running test 29"
../source/grep.exe -E 'a{,3}' ../inputs/grep1.dat  > ../outputs/t29 2>&1

echo ">>>>>>>>running test 30"
../source/grep.exe -E 'a{1,5}' ../inputs/grep1.dat  > ../outputs/t30 2>&1

echo ">>>>>>>>running test 31"
../source/grep.exe -E 'dfaanalyze|ab''[lo]' ../inputs/grep*.dat  > ../outputs/t31 2>&1

echo ">>>>>>>>running test 32"
../source/grep.exe -E '[ab]|include' ../inputs/grep*.dat  > ../outputs/t32 2>&1

echo ">>>>>>>>running test 33"
../source/grep.exe -E '[ab]''le' ../inputs/grep*.dat  > ../outputs/t33 2>&1

echo ">>>>>>>>running test 34"
../source/grep.exe -E '[12]' ../inputs/grep*.dat  > ../outputs/t34 2>&1

echo ">>>>>>>>running test 35"
../source/grep.exe -E 'include|\W''reg' ../inputs/grep*.dat  > ../outputs/t35 2>&1

echo ">>>>>>>>running test 36"
../source/grep.exe -E '[^[:alnum:]]|include' ../inputs/grep*.dat  > ../outputs/t36 2>&1

echo ">>>>>>>>running test 37"
../source/grep.exe -E '[^[:alnum:]]''include' ../inputs/grep*.dat  > ../outputs/t37 2>&1

echo ">>>>>>>>running test 38"
../source/grep.exe -E '[^[:alnum:]]' ../inputs/grep*.dat  > ../outputs/t38 2>&1

echo ">>>>>>>>running test 39"
../source/grep.exe -E 'In.lude|\?''?%' ../inputs/grep*.dat  > ../outputs/t39 2>&1

echo ">>>>>>>>running test 40"
../source/grep.exe -E 'in.lude|\??''%' ../inputs/grep*.dat  > ../outputs/t40 2>&1

echo ">>>>>>>>running test 41"
../source/grep.exe -E 'In.lude|\?(?''%)' ../inputs/grep*.dat  > ../outputs/t41 2>&1

echo ">>>>>>>>running test 42"
../source/grep.exe -Ec 'In.lude|\??' ../inputs/grep*.dat  > ../outputs/t42 2>&1

echo ">>>>>>>>running test 43"
../source/grep.exe -E '\?''?.:' ../inputs/grep*.dat  > ../outputs/t43 2>&1

echo ">>>>>>>>running test 44"
../source/grep.exe -E '\*(?''p.)' ../inputs/grep*.dat  > ../outputs/t44 2>&1

echo ">>>>>>>>running test 45"
../source/grep.exe -E '\*?p.eg' ../inputs/grep*.dat  > ../outputs/t45 2>&1

echo ">>>>>>>>running test 46"
../source/grep.exe -E 'Include|n''?.lud' ../inputs/grep*.dat  > ../outputs/t46 2>&1

echo ">>>>>>>>running test 47"
../source/grep.exe -E 'main|n?''.lud' ../inputs/grep*.dat  > ../outputs/t47 2>&1

echo ">>>>>>>>running test 48"
../source/grep.exe -E 'Include|n(?''.lud)' ../inputs/grep*.dat  > ../outputs/t48 2>&1

echo ">>>>>>>>running test 49"
../source/grep.exe -E 'Include|n?.lude' ../inputs/grep*.dat  > ../outputs/t49 2>&1

echo ">>>>>>>>running test 50"
../source/grep.exe -E 'n''?.lude' ../inputs/grep*.dat  > ../outputs/t50 2>&1

echo ">>>>>>>>running test 51"
../source/grep.exe -E 'n(?''.lud)' ../inputs/grep*.dat  > ../outputs/t51 2>&1

echo ">>>>>>>>running test 52"
../source/grep.exe -E 'n?.lud' ../inputs/grep*.dat  > ../outputs/t52 2>&1

echo ">>>>>>>>running test 53"
../source/grep.exe -E 'In.lude|\?''+%' ../inputs/grep*.dat  > ../outputs/t53 2>&1

echo ">>>>>>>>running test 54"
../source/grep.exe -E 'in.lude|\?+''%' ../inputs/grep*.dat  > ../outputs/t54 2>&1

echo ">>>>>>>>running test 55"
../source/grep.exe -E 'In.lude|\?(+''%)' ../inputs/grep*.dat  > ../outputs/t55 2>&1

echo ">>>>>>>>running test 56"
../source/grep.exe -Ec 'In.lude|\?+' ../inputs/grep*.dat  > ../outputs/t56 2>&1

echo ">>>>>>>>running test 57"
../source/grep.exe -E '\?''+.:' ../inputs/grep*.dat  > ../outputs/t57 2>&1

echo ">>>>>>>>running test 58"
../source/grep.exe -E '\*(+''p.)' ../inputs/grep*.dat  > ../outputs/t58 2>&1

echo ">>>>>>>>running test 59"
../source/grep.exe -E '\*+p.eg' ../inputs/grep*.dat  > ../outputs/t59 2>&1

echo ">>>>>>>>running test 60"
../source/grep.exe -E 'Include|n''+.lud' ../inputs/grep*.dat  > ../outputs/t60 2>&1

echo ">>>>>>>>running test 61"
../source/grep.exe -E 'Include|n+''.lud' ../inputs/grep*.dat  > ../outputs/t61 2>&1

echo ">>>>>>>>running test 62"
../source/grep.exe -E 'Include|n(+''.lud)' ../inputs/grep*.dat  > ../outputs/t62 2>&1

echo ">>>>>>>>running test 63"
../source/grep.exe -E 'Include|n+.lude' ../inputs/grep*.dat  > ../outputs/t63 2>&1

echo ">>>>>>>>running test 64"
../source/grep.exe -E 'n''+.lude' ../inputs/grep*.dat  > ../outputs/t64 2>&1

echo ">>>>>>>>running test 65"
../source/grep.exe -E 'n(+''.lud)' ../inputs/grep*.dat  > ../outputs/t65 2>&1

echo ">>>>>>>>running test 66"
../source/grep.exe -E 'n+.lud' ../inputs/grep*.dat  > ../outputs/t66 2>&1

echo ">>>>>>>>running test 67"
../source/grep.exe -E 'In.lude|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t67 2>&1

echo ">>>>>>>>running test 68"
../source/grep.exe -E 'in.lude|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t68 2>&1

echo ">>>>>>>>running test 69"
../source/grep.exe -E 'In.lude|\?({1}''%)' ../inputs/grep*.dat  > ../outputs/t69 2>&1

echo ">>>>>>>>running test 70"
../source/grep.exe -Ec 'In.lude|\?{1}' ../inputs/grep*.dat  > ../outputs/t70 2>&1

echo ">>>>>>>>running test 71"
../source/grep.exe -E '\?''{1}.:' ../inputs/grep*.dat  > ../outputs/t71 2>&1

echo ">>>>>>>>running test 72"
../source/grep.exe -E '\*({1}''p.)' ../inputs/grep*.dat  > ../outputs/t72 2>&1

echo ">>>>>>>>running test 73"
../source/grep.exe -E '\*{1}p.eg' ../inputs/grep*.dat  > ../outputs/t73 2>&1

echo ">>>>>>>>running test 74"
../source/grep.exe -E 'Include|n''{1}.lud' ../inputs/grep*.dat  > ../outputs/t74 2>&1

echo ">>>>>>>>running test 75"
../source/grep.exe -E 'Include|n{1}''.lud' ../inputs/grep*.dat  > ../outputs/t75 2>&1

echo ">>>>>>>>running test 76"
../source/grep.exe -E 'Include|n({1}''.lud)' ../inputs/grep*.dat  > ../outputs/t76 2>&1

echo ">>>>>>>>running test 77"
../source/grep.exe -E 'Include|n{1}.lude' ../inputs/grep*.dat  > ../outputs/t77 2>&1

echo ">>>>>>>>running test 78"
../source/grep.exe -E 'n''{1}.lude' ../inputs/grep*.dat  > ../outputs/t78 2>&1

echo ">>>>>>>>running test 79"
../source/grep.exe -E 'n({1}''.lud)' ../inputs/grep*.dat  > ../outputs/t79 2>&1

echo ">>>>>>>>running test 80"
../source/grep.exe -E 'n{1}.lud' ../inputs/grep*.dat  > ../outputs/t80 2>&1

echo ">>>>>>>>running test 81"
../source/grep.exe -E 'In.lude|\?''%' ../inputs/grep*.dat  > ../outputs/t81 2>&1

echo ">>>>>>>>running test 82"
../source/grep.exe -Ec 'In.lude|\?' ../inputs/grep*.dat  > ../outputs/t82 2>&1

echo ">>>>>>>>running test 83"
../source/grep.exe -E '\*\*''p.' ../inputs/grep*.dat  > ../outputs/t83 2>&1

echo ">>>>>>>>running test 84"
../source/grep.exe -E '\*p.eg' ../inputs/grep*.dat  > ../outputs/t84 2>&1

echo ">>>>>>>>running test 85"
../source/grep.exe -E 'Include|\?''?%' ../inputs/grep*.dat  > ../outputs/t85 2>&1

echo ">>>>>>>>running test 86"
../source/grep.exe -E 'include|\?''?%' ../inputs/grep*.dat  > ../outputs/t86 2>&1

echo ">>>>>>>>running test 87"
../source/grep.exe -E 'Include|\?(?''%)' ../inputs/grep*.dat  > ../outputs/t87 2>&1

echo ">>>>>>>>running test 88"
../source/grep.exe -Ec 'Include|\??' ../inputs/grep*.dat  > ../outputs/t88 2>&1

echo ">>>>>>>>running test 89"
../source/grep.exe -E '\?''? :' ../inputs/grep*.dat  > ../outputs/t89 2>&1

echo ">>>>>>>>running test 90"
../source/grep.exe -E '\*(?''p)' ../inputs/grep*.dat  > ../outputs/t90 2>&1

echo ">>>>>>>>running test 91"
../source/grep.exe -E '\*?preg' ../inputs/grep*.dat  > ../outputs/t91 2>&1

echo ">>>>>>>>running test 92"
../source/grep.exe -E 'Include|n''?clud' ../inputs/grep*.dat  > ../outputs/t92 2>&1

echo ">>>>>>>>running test 93"
../source/grep.exe -E 'main|in?''clude' ../inputs/grep*.dat  > ../outputs/t93 2>&1

echo ">>>>>>>>running test 94"
../source/grep.exe -E 'Include|n(?''clud)' ../inputs/grep*.dat  > ../outputs/t94 2>&1

echo ">>>>>>>>running test 95"
../source/grep.exe -E 'main|n?clude' ../inputs/grep*.dat  > ../outputs/t95 2>&1

echo ">>>>>>>>running test 96"
../source/grep.exe -E 'n''?clude' ../inputs/grep*.dat  > ../outputs/t96 2>&1

echo ">>>>>>>>running test 97"
../source/grep.exe -E 'n(?''clud)' ../inputs/grep*.dat  > ../outputs/t97 2>&1

echo ">>>>>>>>running test 98"
../source/grep.exe -E 'n?clud' ../inputs/grep*.dat  > ../outputs/t98 2>&1

echo ">>>>>>>>running test 99"
../source/grep.exe -E 'Include|\?''+%' ../inputs/grep*.dat  > ../outputs/t99 2>&1

echo ">>>>>>>>running test 100"
../source/grep.exe -E 'include|\?''+%' ../inputs/grep*.dat  > ../outputs/t100 2>&1

echo ">>>>>>>>running test 101"
../source/grep.exe -E 'Include|\?(+''%)' ../inputs/grep*.dat  > ../outputs/t101 2>&1

echo ">>>>>>>>running test 102"
../source/grep.exe -Ec 'Include|\?+' ../inputs/grep*.dat  > ../outputs/t102 2>&1

echo ">>>>>>>>running test 103"
../source/grep.exe -E '\?''+ 0' ../inputs/grep*.dat  > ../outputs/t103 2>&1

echo ">>>>>>>>running test 104"
../source/grep.exe -E '\*(+''pattern)' ../inputs/grep*.dat  > ../outputs/t104 2>&1

echo ">>>>>>>>running test 105"
../source/grep.exe -E '\*+preg' ../inputs/grep*.dat  > ../outputs/t105 2>&1

echo ">>>>>>>>running test 106"
../source/grep.exe -E 'main|n''+clud' ../inputs/grep*.dat  > ../outputs/t106 2>&1

echo ">>>>>>>>running test 107"
../source/grep.exe -E 'Include|n+''clud' ../inputs/grep*.dat  > ../outputs/t107 2>&1

echo ">>>>>>>>running test 108"
../source/grep.exe -E 'Include|n(+''clud)' ../inputs/grep*.dat  > ../outputs/t108 2>&1

echo ">>>>>>>>running test 109"
../source/grep.exe -E 'Include|n+clude' ../inputs/grep*.dat  > ../outputs/t109 2>&1

echo ">>>>>>>>running test 110"
../source/grep.exe -E 'n''+clude' ../inputs/grep*.dat  > ../outputs/t110 2>&1

echo ">>>>>>>>running test 111"
../source/grep.exe -E 'n(+''clud)' ../inputs/grep*.dat  > ../outputs/t111 2>&1

echo ">>>>>>>>running test 112"
../source/grep.exe -E 'n+clud' ../inputs/grep*.dat  > ../outputs/t112 2>&1

echo ">>>>>>>>running test 113"
../source/grep.exe -E 'Include|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t113 2>&1

echo ">>>>>>>>running test 114"
../source/grep.exe -E 'include|\?{1}''%' ../inputs/grep*.dat  > ../outputs/t114 2>&1

echo ">>>>>>>>running test 115"
../source/grep.exe -E 'Include|\?({1}''%)' ../inputs/grep*.dat  > ../outputs/t115 2>&1

echo ">>>>>>>>running test 116"
../source/grep.exe -Ec 'Include|\?{1}' ../inputs/grep*.dat  > ../outputs/t116 2>&1

echo ">>>>>>>>running test 117"
../source/grep.exe -E '\?''{1} 0' ../inputs/grep*.dat  > ../outputs/t117 2>&1

echo ">>>>>>>>running test 118"
../source/grep.exe -E '\*({1}''pr)' ../inputs/grep*.dat  > ../outputs/t118 2>&1

echo ">>>>>>>>running test 119"
../source/grep.exe -E '\*{1}preg' ../inputs/grep*.dat  > ../outputs/t119 2>&1

echo ">>>>>>>>running test 120"
../source/grep.exe -E 'Include|n''{1}clud' ../inputs/grep*.dat  > ../outputs/t120 2>&1

echo ">>>>>>>>running test 121"
../source/grep.exe -E 'main|n{1}''clud' ../inputs/grep*.dat  > ../outputs/t121 2>&1

echo ">>>>>>>>running test 122"
../source/grep.exe -E 'Include|n({1}''clud)' ../inputs/grep*.dat  > ../outputs/t122 2>&1

echo ">>>>>>>>running test 123"
../source/grep.exe -E 'Include|n{1}clude' ../inputs/grep*.dat  > ../outputs/t123 2>&1

echo ">>>>>>>>running test 124"
../source/grep.exe -E 'n''{1}clude' ../inputs/grep*.dat  > ../outputs/t124 2>&1

echo ">>>>>>>>running test 125"
../source/grep.exe -E 'n({1}''clud)' ../inputs/grep*.dat  > ../outputs/t125 2>&1

echo ">>>>>>>>running test 126"
../source/grep.exe -E 'n{1}clud' ../inputs/grep*.dat  > ../outputs/t126 2>&1

echo ">>>>>>>>running test 127"
../source/grep.exe -E 'Include|\?''%' ../inputs/grep*.dat  > ../outputs/t127 2>&1

echo ">>>>>>>>running test 128"
../source/grep.exe -Ec 'Include|\?' ../inputs/grep*.dat  > ../outputs/t128 2>&1

echo ">>>>>>>>running test 129"
../source/grep.exe -E 'static'' int' ../inputs/grep*.dat  > ../outputs/t129 2>&1

echo ">>>>>>>>running test 130"
../source/grep.exe -E '\*preg' ../inputs/grep*.dat  > ../outputs/t130 2>&1

echo ">>>>>>>>running test 131"
../source/grep.exe -E "[]X]|end"" -" ../inputs/grep*.dat  > ../outputs/t131 2>&1

echo ">>>>>>>>running test 132"
../source/grep.exe -E "[]X]|end" ../inputs/grep*.dat  > ../outputs/t132 2>&1

echo ">>>>>>>>running test 133"
../source/grep.exe -E "[]X]"" -" ../inputs/grep*.dat  > ../outputs/t133 2>&1

echo ">>>>>>>>running test 134"
../source/grep.exe -E "[]X]" ../inputs/grep*.dat  > ../outputs/t134 2>&1

echo ">>>>>>>>running test 135"
../source/grep.exe -E "^if \(?g|if \(""?out" ../inputs/grep*.dat  > ../outputs/t135 2>&1

echo ">>>>>>>>running test 136"
../source/grep.exe -E "^if \(?g|^if \(?""out" ../inputs/grep*.dat  > ../outputs/t136 2>&1

echo ">>>>>>>>running test 137"
../source/grep.exe -E "^if \(?g|^if \((?""out)" ../inputs/grep*.dat  > ../outputs/t137 2>&1

echo ">>>>>>>>running test 138"
../source/grep.exe -E "^if \(?g|^if out" ../inputs/grep*.dat  > ../outputs/t138 2>&1

echo ">>>>>>>>running test 139"
../source/grep.exe -E "^if \(""?gout" ../inputs/grep*.dat  > ../outputs/t139 2>&1

echo ">>>>>>>>running test 140"
../source/grep.exe -E "^if \((?""gout)" ../inputs/grep*.dat  > ../outputs/t140 2>&1

echo ">>>>>>>>running test 141"
../source/grep.exe -E "^if \(?gout" ../inputs/grep*.dat  > ../outputs/t141 2>&1

echo ">>>>>>>>running test 142"
../source/grep.exe -E "^if a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t142 2>&1

echo ">>>>>>>>running test 143"
../source/grep.exe -E "^if a?g|^if a?""out" ../inputs/grep*.dat  > ../outputs/t143 2>&1

echo ">>>>>>>>running test 144"
../source/grep.exe -E "^if a?g|^if a(?""out)" ../inputs/grep*.dat  > ../outputs/t144 2>&1

echo ">>>>>>>>running test 145"
../source/grep.exe -E "^if a?g|^if out" ../inputs/grep*.dat  > ../outputs/t145 2>&1

echo ">>>>>>>>running test 146"
../source/grep.exe -E "^if a""?gout" ../inputs/grep*.dat  > ../outputs/t146 2>&1

echo ">>>>>>>>running test 147"
../source/grep.exe -E "^if a(?""gout)" ../inputs/grep*.dat  > ../outputs/t147 2>&1

echo ">>>>>>>>running test 148"
../source/grep.exe -E "^if a?gout" ../inputs/grep*.dat  > ../outputs/t148 2>&1

echo ">>>>>>>>running test 149"
../source/grep.exe -E "^if \(+g|if \(""+out" ../inputs/grep*.dat  > ../outputs/t149 2>&1

echo ">>>>>>>>running test 150"
../source/grep.exe -E "^if \(+g|^if \(+""out" ../inputs/grep*.dat  > ../outputs/t150 2>&1

echo ">>>>>>>>running test 151"
../source/grep.exe -E "^if \(+g|^if \((+""out)" ../inputs/grep*.dat  > ../outputs/t151 2>&1

echo ">>>>>>>>running test 152"
../source/grep.exe -E "^if \(+g|^if out" ../inputs/grep*.dat  > ../outputs/t152 2>&1

echo ">>>>>>>>running test 153"
../source/grep.exe -E "^if \(""+gout" ../inputs/grep*.dat  > ../outputs/t153 2>&1

echo ">>>>>>>>running test 154"
../source/grep.exe -E "^if \((+""gout)" ../inputs/grep*.dat  > ../outputs/t154 2>&1

echo ">>>>>>>>running test 155"
../source/grep.exe -E "^if \(+gout" ../inputs/grep*.dat  > ../outputs/t155 2>&1

echo ">>>>>>>>running test 156"
../source/grep.exe -E "^if a+g|if a""+out" ../inputs/grep*.dat  > ../outputs/t156 2>&1

echo ">>>>>>>>running test 157"
../source/grep.exe -E "^if a+g|^if a+""out" ../inputs/grep*.dat  > ../outputs/t157 2>&1

echo ">>>>>>>>running test 158"
../source/grep.exe -E "^if a+g|^if a(+""out)" ../inputs/grep*.dat  > ../outputs/t158 2>&1

echo ">>>>>>>>running test 159"
../source/grep.exe -E "^if a+g|^if out" ../inputs/grep*.dat  > ../outputs/t159 2>&1

echo ">>>>>>>>running test 160"
../source/grep.exe -E "^if a""+gout" ../inputs/grep*.dat  > ../outputs/t160 2>&1

echo ">>>>>>>>running test 161"
../source/grep.exe -E "^if a(+""gout)" ../inputs/grep*.dat  > ../outputs/t161 2>&1

echo ">>>>>>>>running test 162"
../source/grep.exe -E "^if a+gout" ../inputs/grep*.dat  > ../outputs/t162 2>&1

echo ">>>>>>>>running test 163"
../source/grep.exe -E "^if \({1}g|if \(""{1}out" ../inputs/grep*.dat  > ../outputs/t163 2>&1

echo ">>>>>>>>running test 164"
../source/grep.exe -E "^if \({1}g|^if \({1}""out" ../inputs/grep*.dat  > ../outputs/t164 2>&1

echo ">>>>>>>>running test 165"
../source/grep.exe -E "^if \({1}g|^if \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t165 2>&1

echo ">>>>>>>>running test 166"
../source/grep.exe -E "^if \({1}g|^if out" ../inputs/grep*.dat  > ../outputs/t166 2>&1

echo ">>>>>>>>running test 167"
../source/grep.exe -E "^if \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t167 2>&1

echo ">>>>>>>>running test 168"
../source/grep.exe -E "^if \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t168 2>&1

echo ">>>>>>>>running test 169"
../source/grep.exe -E "^if \({1}gout" ../inputs/grep*.dat  > ../outputs/t169 2>&1

echo ">>>>>>>>running test 170"
../source/grep.exe -E "^if a{1}g|if a""{1}out" ../inputs/grep*.dat  > ../outputs/t170 2>&1

echo ">>>>>>>>running test 171"
../source/grep.exe -E "^if a{1}g|^if a{1}""out" ../inputs/grep*.dat  > ../outputs/t171 2>&1

echo ">>>>>>>>running test 172"
../source/grep.exe -E "^if a{1}g|^if a({1}""out)" ../inputs/grep*.dat  > ../outputs/t172 2>&1

echo ">>>>>>>>running test 173"
../source/grep.exe -E "^if a{1}g|^if out" ../inputs/grep*.dat  > ../outputs/t173 2>&1

echo ">>>>>>>>running test 174"
../source/grep.exe -E "^if a""{1}gout" ../inputs/grep*.dat  > ../outputs/t174 2>&1

echo ">>>>>>>>running test 175"
../source/grep.exe -E "^if a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t175 2>&1

echo ">>>>>>>>running test 176"
../source/grep.exe -E "^if a{1}gout" ../inputs/grep*.dat  > ../outputs/t176 2>&1

echo ">>>>>>>>running test 177"
../source/grep.exe -E "\<if \(?g|if \(""?out" ../inputs/grep*.dat  > ../outputs/t177 2>&1

echo ">>>>>>>>running test 178"
../source/grep.exe -E "\<if \(?g|\<if \(?""out" ../inputs/grep*.dat  > ../outputs/t178 2>&1

echo ">>>>>>>>running test 179"
../source/grep.exe -E "\<if \(?g|\<if \((?""out)" ../inputs/grep*.dat  > ../outputs/t179 2>&1

echo ">>>>>>>>running test 180"
../source/grep.exe -E "\<if \(?g|\<if out" ../inputs/grep*.dat  > ../outputs/t180 2>&1

echo ">>>>>>>>running test 181"
../source/grep.exe -E "\<if \(""?gout" ../inputs/grep*.dat  > ../outputs/t181 2>&1

echo ">>>>>>>>running test 182"
../source/grep.exe -E "\<if \((?""gout)" ../inputs/grep*.dat  > ../outputs/t182 2>&1

echo ">>>>>>>>running test 183"
../source/grep.exe -E "\<if \(?gout" ../inputs/grep*.dat  > ../outputs/t183 2>&1

echo ">>>>>>>>running test 184"
../source/grep.exe -E "\<if a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t184 2>&1

echo ">>>>>>>>running test 185"
../source/grep.exe -E "\<if a?g|\<if a?""out" ../inputs/grep*.dat  > ../outputs/t185 2>&1

echo ">>>>>>>>running test 186"
../source/grep.exe -E "\<if a?g|\<if a(?""out)" ../inputs/grep*.dat  > ../outputs/t186 2>&1

echo ">>>>>>>>running test 187"
../source/grep.exe -E "\<if a?g|\<if out" ../inputs/grep*.dat  > ../outputs/t187 2>&1

echo ">>>>>>>>running test 188"
../source/grep.exe -E "\<if a""?gout" ../inputs/grep*.dat  > ../outputs/t188 2>&1

echo ">>>>>>>>running test 189"
../source/grep.exe -E "\<if a(?""gout)" ../inputs/grep*.dat  > ../outputs/t189 2>&1

echo ">>>>>>>>running test 190"
../source/grep.exe -E "\<if a?gout" ../inputs/grep*.dat  > ../outputs/t190 2>&1

echo ">>>>>>>>running test 191"
../source/grep.exe -E "\<if \(+g|if \(""+out" ../inputs/grep*.dat  > ../outputs/t191 2>&1

echo ">>>>>>>>running test 192"
../source/grep.exe -E "\<if \(+g|\<if \(+""out" ../inputs/grep*.dat  > ../outputs/t192 2>&1

echo ">>>>>>>>running test 193"
../source/grep.exe -E "\<if \(+g|\<if \((+""out)" ../inputs/grep*.dat  > ../outputs/t193 2>&1

echo ">>>>>>>>running test 194"
../source/grep.exe -E "\<if \(+g|\<if out" ../inputs/grep*.dat  > ../outputs/t194 2>&1

echo ">>>>>>>>running test 195"
../source/grep.exe -E "\<if \(""+gout" ../inputs/grep*.dat  > ../outputs/t195 2>&1

echo ">>>>>>>>running test 196"
../source/grep.exe -E "\<if \((+""gout)" ../inputs/grep*.dat  > ../outputs/t196 2>&1

echo ">>>>>>>>running test 197"
../source/grep.exe -E "\<if \(+gout" ../inputs/grep*.dat  > ../outputs/t197 2>&1

echo ">>>>>>>>running test 198"
../source/grep.exe -E "\<if a+g|if a""+out" ../inputs/grep*.dat  > ../outputs/t198 2>&1

echo ">>>>>>>>running test 199"
../source/grep.exe -E "\<if a+g|\<if a+""out" ../inputs/grep*.dat  > ../outputs/t199 2>&1

echo ">>>>>>>>running test 200"
../source/grep.exe -E "\<if a+g|\<if a(+""out)" ../inputs/grep*.dat  > ../outputs/t200 2>&1

echo ">>>>>>>>running test 201"
../source/grep.exe -E "\<if a+g|\<if out" ../inputs/grep*.dat  > ../outputs/t201 2>&1

echo ">>>>>>>>running test 202"
../source/grep.exe -E "\<if a""+gout" ../inputs/grep*.dat  > ../outputs/t202 2>&1

echo ">>>>>>>>running test 203"
../source/grep.exe -E "\<if a(+""gout)" ../inputs/grep*.dat  > ../outputs/t203 2>&1

echo ">>>>>>>>running test 204"
../source/grep.exe -E "\<if a+gout" ../inputs/grep*.dat  > ../outputs/t204 2>&1

echo ">>>>>>>>running test 205"
../source/grep.exe -E "\<if \({1}g|if \(""{1}out" ../inputs/grep*.dat  > ../outputs/t205 2>&1

echo ">>>>>>>>running test 206"
../source/grep.exe -E "\<if \({1}g|\<if \({1}""out" ../inputs/grep*.dat  > ../outputs/t206 2>&1

echo ">>>>>>>>running test 207"
../source/grep.exe -E "\<if \({1}g|\<if \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t207 2>&1

echo ">>>>>>>>running test 208"
../source/grep.exe -E "\<if \({1}g|\<if out" ../inputs/grep*.dat  > ../outputs/t208 2>&1

echo ">>>>>>>>running test 209"
../source/grep.exe -E "\<if \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t209 2>&1

echo ">>>>>>>>running test 210"
../source/grep.exe -E "\<if \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t210 2>&1

echo ">>>>>>>>running test 211"
../source/grep.exe -E "\<if \({1}gout" ../inputs/grep*.dat  > ../outputs/t211 2>&1

echo ">>>>>>>>running test 212"
../source/grep.exe -E "\<if a{1}g|if a""{1}out" ../inputs/grep*.dat  > ../outputs/t212 2>&1

echo ">>>>>>>>running test 213"
../source/grep.exe -E "\<if a{1}g|\<if a{1}""out" ../inputs/grep*.dat  > ../outputs/t213 2>&1

echo ">>>>>>>>running test 214"
../source/grep.exe -E "\<if a{1}g|\<if a({1}""out)" ../inputs/grep*.dat  > ../outputs/t214 2>&1

echo ">>>>>>>>running test 215"
../source/grep.exe -E "\<if a{1}g|\<if out" ../inputs/grep*.dat  > ../outputs/t215 2>&1

echo ">>>>>>>>running test 216"
../source/grep.exe -E "\<if a""{1}gout" ../inputs/grep*.dat  > ../outputs/t216 2>&1

echo ">>>>>>>>running test 217"
../source/grep.exe -E "\<if a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t217 2>&1

echo ">>>>>>>>running test 218"
../source/grep.exe -E "\<if a{1}gout" ../inputs/grep*.dat  > ../outputs/t218 2>&1

echo ">>>>>>>>running test 219"
../source/grep.exe -E "\bif \(?g|if \(""?out\b" ../inputs/grep*.dat  > ../outputs/t219 2>&1

echo ">>>>>>>>running test 220"
../source/grep.exe -E "\bif \(?g|\bif \(?""out" ../inputs/grep*.dat  > ../outputs/t220 2>&1

echo ">>>>>>>>running test 221"
../source/grep.exe -E "\bif \(?g\b|\bif \((?""out)" ../inputs/grep*.dat  > ../outputs/t221 2>&1

echo ">>>>>>>>running test 222"
../source/grep.exe -E "\bif \(?g\b|\bif out" ../inputs/grep*.dat  > ../outputs/t222 2>&1

echo ">>>>>>>>running test 223"
../source/grep.exe -E "\bif \(""?gout" ../inputs/grep*.dat  > ../outputs/t223 2>&1

echo ">>>>>>>>running test 224"
../source/grep.exe -E "\bif \((?""gout)" ../inputs/grep*.dat  > ../outputs/t224 2>&1

echo ">>>>>>>>running test 225"
../source/grep.exe -E "\bif \(?gout\b" ../inputs/grep*.dat  > ../outputs/t225 2>&1

echo ">>>>>>>>running test 226"
../source/grep.exe -E "\bif a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t226 2>&1

echo ">>>>>>>>running test 227"
../source/grep.exe -E "\bif a?g|\bif a?""out" ../inputs/grep*.dat  > ../outputs/t227 2>&1

echo ">>>>>>>>running test 228"
../source/grep.exe -E "\bif a?g|\bif a(?""out)" ../inputs/grep*.dat  > ../outputs/t228 2>&1

echo ">>>>>>>>running test 229"
../source/grep.exe -E "\bif a?g|\bif out\b" ../inputs/grep*.dat  > ../outputs/t229 2>&1

echo ">>>>>>>>running test 230"
../source/grep.exe -E "\bif a""?gout\b" ../inputs/grep*.dat  > ../outputs/t230 2>&1

echo ">>>>>>>>running test 231"
../source/grep.exe -E "\bif a(?""gout)" ../inputs/grep*.dat  > ../outputs/t231 2>&1

echo ">>>>>>>>running test 232"
../source/grep.exe -E "\bif a?gout" ../inputs/grep*.dat  > ../outputs/t232 2>&1

echo ">>>>>>>>running test 233"
../source/grep.exe -E "\bif \(+g\b|if \(""+out" ../inputs/grep*.dat  > ../outputs/t233 2>&1

echo ">>>>>>>>running test 234"
../source/grep.exe -E "\bif \(+g|\bif \(+""out" ../inputs/grep*.dat  > ../outputs/t234 2>&1

echo ">>>>>>>>running test 235"
../source/grep.exe -E "\bif \(+g|\bif \((+""out)" ../inputs/grep*.dat  > ../outputs/t235 2>&1

echo ">>>>>>>>running test 236"
../source/grep.exe -E "\bif \(+g|\bif out" ../inputs/grep*.dat  > ../outputs/t236 2>&1

echo ">>>>>>>>running test 237"
../source/grep.exe -E "\bif \(""+gout\b" ../inputs/grep*.dat  > ../outputs/t237 2>&1

echo ">>>>>>>>running test 238"
../source/grep.exe -E "\bif \((+""gout)" ../inputs/grep*.dat  > ../outputs/t238 2>&1

echo ">>>>>>>>running test 239"
../source/grep.exe -E "\bif \(+gout" ../inputs/grep*.dat  > ../outputs/t239 2>&1

echo ">>>>>>>>running test 240"
../source/grep.exe -E "\bif a+g\b|if a""+out" ../inputs/grep*.dat  > ../outputs/t240 2>&1

echo ">>>>>>>>running test 241"
../source/grep.exe -E "if a+g\b|\bif a+""out" ../inputs/grep*.dat  > ../outputs/t241 2>&1

echo ">>>>>>>>running test 242"
../source/grep.exe -E "\bif a+g|\bif a(+""out)" ../inputs/grep*.dat  > ../outputs/t242 2>&1

echo ">>>>>>>>running test 243"
../source/grep.exe -E "\bif a+g|\bif out" ../inputs/grep*.dat  > ../outputs/t243 2>&1

echo ">>>>>>>>running test 244"
../source/grep.exe -E "if a""+gout\b" ../inputs/grep*.dat  > ../outputs/t244 2>&1

echo ">>>>>>>>running test 245"
../source/grep.exe -E "\bif a(+""gout)" ../inputs/grep*.dat  > ../outputs/t245 2>&1

echo ">>>>>>>>running test 246"
../source/grep.exe -E "if a+gout\b" ../inputs/grep*.dat  > ../outputs/t246 2>&1

echo ">>>>>>>>running test 247"
../source/grep.exe -E "\bif \({1}g|if \(""{1}out\b" ../inputs/grep*.dat  > ../outputs/t247 2>&1

echo ">>>>>>>>running test 248"
../source/grep.exe -E "\bif \({1}g|\bif \({1}""out" ../inputs/grep*.dat  > ../outputs/t248 2>&1

echo ">>>>>>>>running test 249"
../source/grep.exe -E "if \({1}g\b|\bif \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t249 2>&1

echo ">>>>>>>>running test 250"
../source/grep.exe -E "\bif \({1}g|\bif out" ../inputs/grep*.dat  > ../outputs/t250 2>&1

echo ">>>>>>>>running test 251"
../source/grep.exe -E "\bif \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t251 2>&1

echo ">>>>>>>>running test 252"
../source/grep.exe -E "\bif \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t252 2>&1

echo ">>>>>>>>running test 253"
../source/grep.exe -E "\bif \({1}gout\b" ../inputs/grep*.dat  > ../outputs/t253 2>&1

echo ">>>>>>>>running test 254"
../source/grep.exe -E "\bif a{1}g|if a""{1}out\b" ../inputs/grep*.dat  > ../outputs/t254 2>&1

echo ">>>>>>>>running test 255"
../source/grep.exe -E "\bif a{1}g|\bif a{1}""out" ../inputs/grep*.dat  > ../outputs/t255 2>&1

echo ">>>>>>>>running test 256"
../source/grep.exe -E "\bif a{1}g|\bif a({1}""out)" ../inputs/grep*.dat  > ../outputs/t256 2>&1

echo ">>>>>>>>running test 257"
../source/grep.exe -E "if a{1}g\b|\bif out" ../inputs/grep*.dat  > ../outputs/t257 2>&1

echo ">>>>>>>>running test 258"
../source/grep.exe -E "\bif a""{1}gout" ../inputs/grep*.dat  > ../outputs/t258 2>&1

echo ">>>>>>>>running test 259"
../source/grep.exe -E "\bif a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t259 2>&1

echo ">>>>>>>>running test 260"
../source/grep.exe -E "if a{1}gout\b" ../inputs/grep*.dat  > ../outputs/t260 2>&1

echo ">>>>>>>>running test 261"
../source/grep.exe -Ec static ../inputs/grep*.dat  > ../outputs/t261 2>&1

echo ">>>>>>>>running test 262"
../source/grep.exe -F 'if (out)' ../inputs/grep*.dat  > ../outputs/t262 2>&1

echo ">>>>>>>>running test 263"
../source/grep.exe -F "if (gout)" ../inputs/grep*.dat  > ../outputs/t263 2>&1

echo ">>>>>>>>running test 264"
../source/grep.exe -F agout ../inputs/grep*.dat  > ../outputs/t264 2>&1

echo ">>>>>>>>running test 265"
../source/grep.exe -G 'dfaanalyze\|ab''[lo]' ../inputs/grep*.dat  > ../outputs/t265 2>&1

echo ">>>>>>>>running test 266"
../source/grep.exe -G '\(dfaanalyze\|ab\)''[lo]' ../inputs/grep*.dat  > ../outputs/t266 2>&1

echo ">>>>>>>>running test 267"
../source/grep.exe -G '[ab]\|include' ../inputs/grep*.dat  > ../outputs/t267 2>&1

echo ">>>>>>>>running test 268"
../source/grep.exe '[ab]''le' ../inputs/grep*.dat  > ../outputs/t268 2>&1

echo ">>>>>>>>running test 269"
../source/grep.exe -G '[12]' ../inputs/grep*.dat  > ../outputs/t269 2>&1

echo ">>>>>>>>running test 270"
../source/grep.exe -G 'include\|\W''reg' ../inputs/grep*.dat  > ../outputs/t270 2>&1

echo ">>>>>>>>running test 271"
../source/grep.exe -G '\(include\|\W\)''reg' ../inputs/grep*.dat  > ../outputs/t271 2>&1

echo ">>>>>>>>running test 272"
../source/grep.exe '[^[:alnum:]]\|include' ../inputs/grep*.dat  > ../outputs/t272 2>&1

echo ">>>>>>>>running test 273"
../source/grep.exe -G '[^[:alnum:]]''include' ../inputs/grep*.dat  > ../outputs/t273 2>&1

echo ">>>>>>>>running test 274"
../source/grep.exe -G '[^[:alnum:]]' ../inputs/grep*.dat  > ../outputs/t274 2>&1

echo ">>>>>>>>running test 275"
../source/grep.exe -G 'In.lude\|?''\?%' ../inputs/grep*.dat  > ../outputs/t275 2>&1

echo ">>>>>>>>running test 276"
../source/grep.exe -G 'in.lude\|?\?''%' ../inputs/grep*.dat  > ../outputs/t276 2>&1

echo ">>>>>>>>running test 277"
../source/grep.exe -G '\(in.lude\|?\?\)''%' ../inputs/grep*.dat  > ../outputs/t277 2>&1

echo ">>>>>>>>running test 278"
../source/grep.exe -Gc 'In.lude\|?\?' ../inputs/grep*.dat  > ../outputs/t278 2>&1

echo ">>>>>>>>running test 279"
../source/grep.exe -G '?''\?.:' ../inputs/grep*.dat  > ../outputs/t279 2>&1

echo ">>>>>>>>running test 280"
../source/grep.exe -G '\*\?p.eg' ../inputs/grep*.dat  > ../outputs/t280 2>&1

echo ">>>>>>>>running test 281"
../source/grep.exe -G 'Include\|n''\?.lud' ../inputs/grep*.dat  > ../outputs/t281 2>&1

echo ">>>>>>>>running test 282"
../source/grep.exe -G 'main\|n\?''.lud' ../inputs/grep*.dat  > ../outputs/t282 2>&1

echo ">>>>>>>>running test 283"
../source/grep.exe -G '\(main\|n\?\)''.lud' ../inputs/grep*.dat  > ../outputs/t283 2>&1

echo ">>>>>>>>running test 284"
../source/grep.exe 'Include\|n\?.lude' ../inputs/grep*.dat  > ../outputs/t284 2>&1

echo ">>>>>>>>running test 285"
../source/grep.exe -G 'n''\?.lude' ../inputs/grep*.dat  > ../outputs/t285 2>&1

echo ">>>>>>>>running test 286"
../source/grep.exe -G 'n\?.lud' ../inputs/grep*.dat  > ../outputs/t286 2>&1

echo ">>>>>>>>running test 287"
../source/grep.exe -G 'In.lude\|?''\+%' ../inputs/grep*.dat  > ../outputs/t287 2>&1

echo ">>>>>>>>running test 288"
../source/grep.exe -G 'in.lude\|?\+''%' ../inputs/grep*.dat  > ../outputs/t288 2>&1

echo ">>>>>>>>running test 289"
../source/grep.exe -G '\(in.lude\|?\+\)''%' ../inputs/grep*.dat  > ../outputs/t289 2>&1

echo ">>>>>>>>running test 290"
../source/grep.exe -Gc 'In.lude\|?\+' ../inputs/grep*.dat  > ../outputs/t290 2>&1

echo ">>>>>>>>running test 291"
../source/grep.exe -G '?''\+.:' ../inputs/grep*.dat  > ../outputs/t291 2>&1

echo ">>>>>>>>running test 292"
../source/grep.exe '\*\+p.eg' ../inputs/grep*.dat  > ../outputs/t292 2>&1

echo ">>>>>>>>running test 293"
../source/grep.exe -G 'Include\|n''\+.lud' ../inputs/grep*.dat  > ../outputs/t293 2>&1

echo ">>>>>>>>running test 294"
../source/grep.exe -G 'Include\|n\+''.lud' ../inputs/grep*.dat  > ../outputs/t294 2>&1

echo ">>>>>>>>running test 295"
../source/grep.exe -G '\(Include\|n\+\)''.lud' ../inputs/grep*.dat  > ../outputs/t295 2>&1

echo ">>>>>>>>running test 296"
../source/grep.exe -G 'Include\|n\+.lude' ../inputs/grep*.dat  > ../outputs/t296 2>&1

echo ">>>>>>>>running test 297"
../source/grep.exe 'n''\+.lude' ../inputs/grep*.dat  > ../outputs/t297 2>&1

echo ">>>>>>>>running test 298"
../source/grep.exe 'n\+.lud' ../inputs/grep*.dat  > ../outputs/t298 2>&1

echo ">>>>>>>>running test 299"
../source/grep.exe -G 'In.lude\|?''\{1\}%' ../inputs/grep*.dat  > ../outputs/t299 2>&1

echo ">>>>>>>>running test 300"
../source/grep.exe -G 'in.lude\|?\{1\}''%' ../inputs/grep*.dat  > ../outputs/t300 2>&1

echo ">>>>>>>>running test 301"
../source/grep.exe -G '\(in.lude\|?\{1\}\)''%' ../inputs/grep*.dat  > ../outputs/t301 2>&1

echo ">>>>>>>>running test 302"
../source/grep.exe -c 'In.lude\|?\{1\}' ../inputs/grep*.dat  > ../outputs/t302 2>&1

echo ">>>>>>>>running test 303"
../source/grep.exe -G '?''\{1\}.:' ../inputs/grep*.dat  > ../outputs/t303 2>&1

echo ">>>>>>>>running test 304"
../source/grep.exe -G '\*\{1\}p.eg' ../inputs/grep*.dat  > ../outputs/t304 2>&1

echo ">>>>>>>>running test 305"
../source/grep.exe -G 'Include\|n''\{1\}.lud' ../inputs/grep*.dat  > ../outputs/t305 2>&1

echo ">>>>>>>>running test 306"
../source/grep.exe 'Include\|n\{1\}''.lud' ../inputs/grep*.dat  > ../outputs/t306 2>&1

echo ">>>>>>>>running test 307"
../source/grep.exe '\(Include\|n\{1\}\)''.lud' ../inputs/grep*.dat  > ../outputs/t307 2>&1

echo ">>>>>>>>running test 308"
../source/grep.exe -G 'Include\|n\{1\}.lude' ../inputs/grep*.dat  > ../outputs/t308 2>&1

echo ">>>>>>>>running test 309"
../source/grep.exe 'n''\{1\}.lude' ../inputs/grep*.dat  > ../outputs/t309 2>&1

echo ">>>>>>>>running test 310"
../source/grep.exe -G 'n\{1\}.lud' ../inputs/grep*.dat  > ../outputs/t310 2>&1

echo ">>>>>>>>running test 311"
../source/grep.exe 'In.lude\|?''%' ../inputs/grep*.dat  > ../outputs/t311 2>&1

echo ">>>>>>>>running test 312"
../source/grep.exe '\(In.lude\|?\)''%' ../inputs/grep*.dat  > ../outputs/t312 2>&1

echo ">>>>>>>>running test 313"
../source/grep.exe -Gc 'In.lude\|?' ../inputs/grep*.dat  > ../outputs/t313 2>&1

echo ">>>>>>>>running test 314"
../source/grep.exe '\*\*''p.' ../inputs/grep*.dat  > ../outputs/t314 2>&1

echo ">>>>>>>>running test 315"
../source/grep.exe -G '\*p.eg' ../inputs/grep*.dat  > ../outputs/t315 2>&1

echo ">>>>>>>>running test 316"
../source/grep.exe -G 'Include\|?''\?%' ../inputs/grep*.dat  > ../outputs/t316 2>&1

echo ">>>>>>>>running test 317"
../source/grep.exe -G 'include\|?\?''%' ../inputs/grep*.dat  > ../outputs/t317 2>&1

echo ">>>>>>>>running test 318"
../source/grep.exe -G '\(include\|?\?\)''%' ../inputs/grep*.dat  > ../outputs/t318 2>&1

echo ">>>>>>>>running test 319"
../source/grep.exe -Gc 'Include\|?\?' ../inputs/grep*.dat  > ../outputs/t319 2>&1

echo ">>>>>>>>running test 320"
../source/grep.exe -G '?''\? :' ../inputs/grep*.dat  > ../outputs/t320 2>&1

echo ">>>>>>>>running test 321"
../source/grep.exe -G '\*\?preg' ../inputs/grep*.dat  > ../outputs/t321 2>&1

echo ">>>>>>>>running test 322"
../source/grep.exe -G 'Include\|n''\?clud' ../inputs/grep*.dat  > ../outputs/t322 2>&1

echo ">>>>>>>>running test 323"
../source/grep.exe 'main\|in\?''clude' ../inputs/grep*.dat  > ../outputs/t323 2>&1

echo ">>>>>>>>running test 324"
../source/grep.exe '\(main\|in\?\)''clude' ../inputs/grep*.dat  > ../outputs/t324 2>&1

echo ">>>>>>>>running test 325"
../source/grep.exe -G 'main\|n\?clude' ../inputs/grep*.dat  > ../outputs/t325 2>&1

echo ">>>>>>>>running test 326"
../source/grep.exe -G 'n''\?clude' ../inputs/grep*.dat  > ../outputs/t326 2>&1

echo ">>>>>>>>running test 327"
../source/grep.exe -G 'n\?clud' ../inputs/grep*.dat  > ../outputs/t327 2>&1

echo ">>>>>>>>running test 328"
../source/grep.exe -G 'Include\|?''\+%' ../inputs/grep*.dat  > ../outputs/t328 2>&1

echo ">>>>>>>>running test 329"
../source/grep.exe -G 'include\|?\+''%' ../inputs/grep*.dat  > ../outputs/t329 2>&1

echo ">>>>>>>>running test 330"
../source/grep.exe -G '\(include\|?\+\)''%' ../inputs/grep*.dat  > ../outputs/t330 2>&1

echo ">>>>>>>>running test 331"
../source/grep.exe -Gc 'Include\|?\+' ../inputs/grep*.dat  > ../outputs/t331 2>&1

echo ">>>>>>>>running test 332"
../source/grep.exe -G '?''\+ 0' ../inputs/grep*.dat  > ../outputs/t332 2>&1

echo ">>>>>>>>running test 333"
../source/grep.exe -G '\*\+preg' ../inputs/grep*.dat  > ../outputs/t333 2>&1

echo ">>>>>>>>running test 334"
../source/grep.exe -G 'main\|n''\+clud' ../inputs/grep*.dat  > ../outputs/t334 2>&1

echo ">>>>>>>>running test 335"
../source/grep.exe -G 'Include\|n\+''clud' ../inputs/grep*.dat  > ../outputs/t335 2>&1

echo ">>>>>>>>running test 336"
../source/grep.exe -G '\(Include\|n\+\)''clud' ../inputs/grep*.dat  > ../outputs/t336 2>&1

echo ">>>>>>>>running test 337"
../source/grep.exe -G 'Include\|n\+clude' ../inputs/grep*.dat  > ../outputs/t337 2>&1

echo ">>>>>>>>running test 338"
../source/grep.exe -G 'n''\+clude' ../inputs/grep*.dat  > ../outputs/t338 2>&1

echo ">>>>>>>>running test 339"
../source/grep.exe -G 'n\+clud' ../inputs/grep*.dat  > ../outputs/t339 2>&1

echo ">>>>>>>>running test 340"
../source/grep.exe -G 'Include\|?''\{1\}%' ../inputs/grep*.dat  > ../outputs/t340 2>&1

echo ">>>>>>>>running test 341"
../source/grep.exe -G 'include\|?\{1\}''%' ../inputs/grep*.dat  > ../outputs/t341 2>&1

echo ">>>>>>>>running test 342"
../source/grep.exe -G '\(include\|?\{1\}\)''%' ../inputs/grep*.dat  > ../outputs/t342 2>&1

echo ">>>>>>>>running test 343"
../source/grep.exe -Gc 'Include\|?\{1\}' ../inputs/grep*.dat  > ../outputs/t343 2>&1

echo ">>>>>>>>running test 344"
../source/grep.exe -G '?''\{1\} 0' ../inputs/grep*.dat  > ../outputs/t344 2>&1

echo ">>>>>>>>running test 345"
../source/grep.exe '\*\{1\}preg' ../inputs/grep*.dat  > ../outputs/t345 2>&1

echo ">>>>>>>>running test 346"
../source/grep.exe 'Include\|n''\{1\}clud' ../inputs/grep*.dat  > ../outputs/t346 2>&1

echo ">>>>>>>>running test 347"
../source/grep.exe -G 'main\|n\{1\}''clud' ../inputs/grep*.dat  > ../outputs/t347 2>&1

echo ">>>>>>>>running test 348"
../source/grep.exe -G '\(main\|n\{1\}\)''clud' ../inputs/grep*.dat  > ../outputs/t348 2>&1

echo ">>>>>>>>running test 349"
../source/grep.exe -G 'Include\|n\{1\}clude' ../inputs/grep*.dat  > ../outputs/t349 2>&1

echo ">>>>>>>>running test 350"
../source/grep.exe -G 'n''\{1\}clude' ../inputs/grep*.dat  > ../outputs/t350 2>&1

echo ">>>>>>>>running test 351"
../source/grep.exe 'n\{1\}clud' ../inputs/grep*.dat  > ../outputs/t351 2>&1

echo ">>>>>>>>running test 352"
../source/grep.exe -G 'Include\|?''%' ../inputs/grep*.dat  > ../outputs/t352 2>&1

echo ">>>>>>>>running test 353"
../source/grep.exe -G '\(Include\|?\)''%' ../inputs/grep*.dat  > ../outputs/t353 2>&1

echo ">>>>>>>>running test 354"
../source/grep.exe -Gc 'Include\|?' ../inputs/grep*.dat  > ../outputs/t354 2>&1

echo ">>>>>>>>running test 355"
../source/grep.exe -G 'static'' int' ../inputs/grep*.dat  > ../outputs/t355 2>&1

echo ">>>>>>>>running test 356"
../source/grep.exe '\*preg' ../inputs/grep*.dat  > ../outputs/t356 2>&1

echo ">>>>>>>>running test 357"
../source/grep.exe -G "[]X]\|end"" -" ../inputs/grep*.dat  > ../outputs/t357 2>&1

echo ">>>>>>>>running test 358"
../source/grep.exe -G "\([]X]\|end\)"" -" ../inputs/grep*.dat  > ../outputs/t358 2>&1

echo ">>>>>>>>running test 359"
../source/grep.exe -G "[]X]\|end" ../inputs/grep*.dat  > ../outputs/t359 2>&1

echo ">>>>>>>>running test 360"
../source/grep.exe "[]X]"" -" ../inputs/grep*.dat  > ../outputs/t360 2>&1

echo ">>>>>>>>running test 361"
../source/grep.exe -G "[]X]" ../inputs/grep*.dat  > ../outputs/t361 2>&1

echo ">>>>>>>>running test 362"
../source/grep.exe -G "^if (\?g\|if (""\?out" ../inputs/grep*.dat  > ../outputs/t362 2>&1

echo ">>>>>>>>running test 363"
../source/grep.exe -G "^if (\?g\|^if (\?""out" ../inputs/grep*.dat  > ../outputs/t363 2>&1

echo ">>>>>>>>running test 364"
../source/grep.exe -G "\(^if (\?g\|^if (\?\)""out" ../inputs/grep*.dat  > ../outputs/t364 2>&1

echo ">>>>>>>>running test 365"
../source/grep.exe -G "^if (\?g\|^if out" ../inputs/grep*.dat  > ../outputs/t365 2>&1

echo ">>>>>>>>running test 366"
../source/grep.exe -G "^if (""\?gout" ../inputs/grep*.dat  > ../outputs/t366 2>&1

echo ">>>>>>>>running test 367"
../source/grep.exe "^if (\?gout" ../inputs/grep*.dat  > ../outputs/t367 2>&1

echo ">>>>>>>>running test 368"
../source/grep.exe -G "^if a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t368 2>&1

echo ">>>>>>>>running test 369"
../source/grep.exe -G "^if a\?g\|^if a\?""out" ../inputs/grep*.dat  > ../outputs/t369 2>&1

echo ">>>>>>>>running test 370"
../source/grep.exe -G "\(^if a\?g\|^if a\?\)""out" ../inputs/grep*.dat  > ../outputs/t370 2>&1

echo ">>>>>>>>running test 371"
../source/grep.exe -G "^if a\?g\|^if out" ../inputs/grep*.dat  > ../outputs/t371 2>&1

echo ">>>>>>>>running test 372"
../source/grep.exe -G "^if a""\?gout" ../inputs/grep*.dat  > ../outputs/t372 2>&1

echo ">>>>>>>>running test 373"
../source/grep.exe -G "^if a\?gout" ../inputs/grep*.dat  > ../outputs/t373 2>&1

echo ">>>>>>>>running test 374"
../source/grep.exe -G "^if (\+g\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t374 2>&1

echo ">>>>>>>>running test 375"
../source/grep.exe -G "^if (\+g\|^if (\+""out" ../inputs/grep*.dat  > ../outputs/t375 2>&1

echo ">>>>>>>>running test 376"
../source/grep.exe -G "\(^if (\+g\|^if (\+\)""out" ../inputs/grep*.dat  > ../outputs/t376 2>&1

echo ">>>>>>>>running test 377"
../source/grep.exe -G "^if (\+g\|^if out" ../inputs/grep*.dat  > ../outputs/t377 2>&1

echo ">>>>>>>>running test 378"
../source/grep.exe -G "^if (""\+gout" ../inputs/grep*.dat  > ../outputs/t378 2>&1

echo ">>>>>>>>running test 379"
../source/grep.exe -G "^if (\+gout" ../inputs/grep*.dat  > ../outputs/t379 2>&1

echo ">>>>>>>>running test 380"
../source/grep.exe -G "^if a\+g\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t380 2>&1

echo ">>>>>>>>running test 381"
../source/grep.exe -G "^if a\+g\|^if a\+""out" ../inputs/grep*.dat  > ../outputs/t381 2>&1

echo ">>>>>>>>running test 382"
../source/grep.exe -G "\(^if a\+g\|^if a\+\)""out" ../inputs/grep*.dat  > ../outputs/t382 2>&1

echo ">>>>>>>>running test 383"
../source/grep.exe "^if a\+g\|^if out" ../inputs/grep*.dat  > ../outputs/t383 2>&1

echo ">>>>>>>>running test 384"
../source/grep.exe -G "^if a""\+gout" ../inputs/grep*.dat  > ../outputs/t384 2>&1

echo ">>>>>>>>running test 385"
../source/grep.exe -G "^if a\+gout" ../inputs/grep*.dat  > ../outputs/t385 2>&1

echo ">>>>>>>>running test 386"
../source/grep.exe -G "^if (\{1\}g\|if (""\{1\}out" ../inputs/grep*.dat  > ../outputs/t386 2>&1

echo ">>>>>>>>running test 387"
../source/grep.exe -G "^if (\{1\}g\|^if (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t387 2>&1

echo ">>>>>>>>running test 388"
../source/grep.exe -G "\(^if (\{1\}g\|^if (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t388 2>&1

echo ">>>>>>>>running test 389"
../source/grep.exe -G "^if (\{1\}g\|^if out" ../inputs/grep*.dat  > ../outputs/t389 2>&1

echo ">>>>>>>>running test 390"
../source/grep.exe -G "^if (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t390 2>&1

echo ">>>>>>>>running test 391"
../source/grep.exe -G "^if (\{1\}gout" ../inputs/grep*.dat  > ../outputs/t391 2>&1

echo ">>>>>>>>running test 392"
../source/grep.exe -G "^if a\{1\}g\|if a""\{1\}out" ../inputs/grep*.dat  > ../outputs/t392 2>&1

echo ">>>>>>>>running test 393"
../source/grep.exe "^if a\{1\}g\|^if a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t393 2>&1

echo ">>>>>>>>running test 394"
../source/grep.exe "\(^if a\{1\}g\|^if a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t394 2>&1

echo ">>>>>>>>running test 395"
../source/grep.exe -G "^if a\{1\}g\|^if out" ../inputs/grep*.dat  > ../outputs/t395 2>&1

echo ">>>>>>>>running test 396"
../source/grep.exe "^if a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t396 2>&1

echo ">>>>>>>>running test 397"
../source/grep.exe "^if a\{1\}gout" ../inputs/grep*.dat  > ../outputs/t397 2>&1

echo ">>>>>>>>running test 398"
../source/grep.exe -G "\<if (\?g\|if (""\?out" ../inputs/grep*.dat  > ../outputs/t398 2>&1

echo ">>>>>>>>running test 399"
../source/grep.exe -G "\<if (\?g\|\<if (\?""out" ../inputs/grep*.dat  > ../outputs/t399 2>&1

echo ">>>>>>>>running test 400"
../source/grep.exe -G "\(\<if (\?g\|\<if (\?\)""out" ../inputs/grep*.dat  > ../outputs/t400 2>&1

echo ">>>>>>>>running test 401"
../source/grep.exe -G "\<if (\?g\|\<if out" ../inputs/grep*.dat  > ../outputs/t401 2>&1

echo ">>>>>>>>running test 402"
../source/grep.exe -G "\<if (""\?gout" ../inputs/grep*.dat  > ../outputs/t402 2>&1

echo ">>>>>>>>running test 403"
../source/grep.exe -G "\<if (\?gout" ../inputs/grep*.dat  > ../outputs/t403 2>&1

echo ">>>>>>>>running test 404"
../source/grep.exe "\<if a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t404 2>&1

echo ">>>>>>>>running test 405"
../source/grep.exe -G "\<if a\?g\|\<if a\?""out" ../inputs/grep*.dat  > ../outputs/t405 2>&1

echo ">>>>>>>>running test 406"
../source/grep.exe -G "\(\<if a\?g\|\<if a\?\)""out" ../inputs/grep*.dat  > ../outputs/t406 2>&1

echo ">>>>>>>>running test 407"
../source/grep.exe -G "\<if a\?g\|\<if out" ../inputs/grep*.dat  > ../outputs/t407 2>&1

echo ">>>>>>>>running test 408"
../source/grep.exe "\<if a""\?gout" ../inputs/grep*.dat  > ../outputs/t408 2>&1

echo ">>>>>>>>running test 409"
../source/grep.exe -G "\<if a\?gout" ../inputs/grep*.dat  > ../outputs/t409 2>&1

echo ">>>>>>>>running test 410"
../source/grep.exe -G "\<if (\+g\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t410 2>&1

echo ">>>>>>>>running test 411"
../source/grep.exe -G "\<if (\+g\|\<if (\+""out" ../inputs/grep*.dat  > ../outputs/t411 2>&1

echo ">>>>>>>>running test 412"
../source/grep.exe -G "\(\<if (\+g\|\<if (\+\)""out" ../inputs/grep*.dat  > ../outputs/t412 2>&1

echo ">>>>>>>>running test 413"
../source/grep.exe -G "\<if (\+g\|\<if out" ../inputs/grep*.dat  > ../outputs/t413 2>&1

echo ">>>>>>>>running test 414"
../source/grep.exe -G "\<if (""\+gout" ../inputs/grep*.dat  > ../outputs/t414 2>&1

echo ">>>>>>>>running test 415"
../source/grep.exe -G "\<if (\+gout" ../inputs/grep*.dat  > ../outputs/t415 2>&1

echo ">>>>>>>>running test 416"
../source/grep.exe -G "\<if a\+g\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t416 2>&1

echo ">>>>>>>>running test 417"
../source/grep.exe -G "\<if a\+g\|\<if a\+""out" ../inputs/grep*.dat  > ../outputs/t417 2>&1

echo ">>>>>>>>running test 418"
../source/grep.exe -G "\(\<if a\+g\|\<if a\+\)""out" ../inputs/grep*.dat  > ../outputs/t418 2>&1

echo ">>>>>>>>running test 419"
../source/grep.exe -G "\<if a\+g\|\<if out" ../inputs/grep*.dat  > ../outputs/t419 2>&1

echo ">>>>>>>>running test 420"
../source/grep.exe "\<if a""\+gout" ../inputs/grep*.dat  > ../outputs/t420 2>&1

echo ">>>>>>>>running test 421"
../source/grep.exe -G "\<if a\+gout" ../inputs/grep*.dat  > ../outputs/t421 2>&1

echo ">>>>>>>>running test 422"
../source/grep.exe -G "\<if (\{1\}g\|if (""\{1\}out" ../inputs/grep*.dat  > ../outputs/t422 2>&1

echo ">>>>>>>>running test 423"
../source/grep.exe -G "\<if (\{1\}g\|\<if (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t423 2>&1

echo ">>>>>>>>running test 424"
../source/grep.exe -G "\(\<if (\{1\}g\|\<if (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t424 2>&1

echo ">>>>>>>>running test 425"
../source/grep.exe -G "\<if (\{1\}g\|\<if out" ../inputs/grep*.dat  > ../outputs/t425 2>&1

echo ">>>>>>>>running test 426"
../source/grep.exe "\<if (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t426 2>&1

echo ">>>>>>>>running test 427"
../source/grep.exe -G "\<if (\{1\}gout" ../inputs/grep*.dat  > ../outputs/t427 2>&1

echo ">>>>>>>>running test 428"
../source/grep.exe -G "\<if a\{1\}g\|if a""\{1\}out" ../inputs/grep*.dat  > ../outputs/t428 2>&1

echo ">>>>>>>>running test 429"
../source/grep.exe -G "\<if a\{1\}g\|\<if a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t429 2>&1

echo ">>>>>>>>running test 430"
../source/grep.exe -G "\(\<if a\{1\}g\|\<if a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t430 2>&1

echo ">>>>>>>>running test 431"
../source/grep.exe -G "\<if a\{1\}g\|\<if out" ../inputs/grep*.dat  > ../outputs/t431 2>&1

echo ">>>>>>>>running test 432"
../source/grep.exe -G "\<if a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t432 2>&1

echo ">>>>>>>>running test 433"
../source/grep.exe -G "\<if a\{1\}gout" ../inputs/grep*.dat  > ../outputs/t433 2>&1

echo ">>>>>>>>running test 434"
../source/grep.exe "\bif (\?g\|if (""\?out\b" ../inputs/grep*.dat  > ../outputs/t434 2>&1

echo ">>>>>>>>running test 435"
../source/grep.exe -G "\bif (\?g\|\bif (\?""out" ../inputs/grep*.dat  > ../outputs/t435 2>&1

echo ">>>>>>>>running test 436"
../source/grep.exe -G "\(\bif (\?g\|\bif (\?\)""out" ../inputs/grep*.dat  > ../outputs/t436 2>&1

echo ">>>>>>>>running test 437"
../source/grep.exe "\bif (\?g\b\|\bif out" ../inputs/grep*.dat  > ../outputs/t437 2>&1

echo ">>>>>>>>running test 438"
../source/grep.exe -G "\bif (""\?gout" ../inputs/grep*.dat  > ../outputs/t438 2>&1

echo ">>>>>>>>running test 439"
../source/grep.exe -G "\bif (\?gout\b" ../inputs/grep*.dat  > ../outputs/t439 2>&1

echo ">>>>>>>>running test 440"
../source/grep.exe -G "\bif a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t440 2>&1

echo ">>>>>>>>running test 441"
../source/grep.exe "\bif a\?g\|\bif a\?""out" ../inputs/grep*.dat  > ../outputs/t441 2>&1

echo ">>>>>>>>running test 442"
../source/grep.exe "\(\bif a\?g\|\bif a\?\)""out" ../inputs/grep*.dat  > ../outputs/t442 2>&1

echo ">>>>>>>>running test 443"
../source/grep.exe -G "\bif a\?g\|\bif out\b" ../inputs/grep*.dat  > ../outputs/t443 2>&1

echo ">>>>>>>>running test 444"
../source/grep.exe -G "\bif a""\?gout\b" ../inputs/grep*.dat  > ../outputs/t444 2>&1

echo ">>>>>>>>running test 445"
../source/grep.exe -G "\bif a\?gout" ../inputs/grep*.dat  > ../outputs/t445 2>&1

echo ">>>>>>>>running test 446"
../source/grep.exe -G "\bif (\+g\b\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t446 2>&1

echo ">>>>>>>>running test 447"
../source/grep.exe "\bif (\+g\|\bif (\+""out" ../inputs/grep*.dat  > ../outputs/t447 2>&1

echo ">>>>>>>>running test 448"
../source/grep.exe "\(\bif (\+g\|\bif (\+\)""out" ../inputs/grep*.dat  > ../outputs/t448 2>&1

echo ">>>>>>>>running test 449"
../source/grep.exe -G "\bif (\+g\|\bif out" ../inputs/grep*.dat  > ../outputs/t449 2>&1

echo ">>>>>>>>running test 450"
../source/grep.exe -G "\bif (""\+gout\b" ../inputs/grep*.dat  > ../outputs/t450 2>&1

echo ">>>>>>>>running test 451"
../source/grep.exe -G "\bif (\+gout" ../inputs/grep*.dat  > ../outputs/t451 2>&1

echo ">>>>>>>>running test 452"
../source/grep.exe -G "\bif a\+g\b\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t452 2>&1

echo ">>>>>>>>running test 453"
../source/grep.exe -G "if a\+g\b\|\bif a\+""out" ../inputs/grep*.dat  > ../outputs/t453 2>&1

echo ">>>>>>>>running test 454"
../source/grep.exe -G "\(if a\+g\b\|\bif a\+\)""out" ../inputs/grep*.dat  > ../outputs/t454 2>&1

echo ">>>>>>>>running test 455"
../source/grep.exe -G "\bif a\+g\|\bif out" ../inputs/grep*.dat  > ../outputs/t455 2>&1

echo ">>>>>>>>running test 456"
../source/grep.exe -G "if a""\+gout\b" ../inputs/grep*.dat  > ../outputs/t456 2>&1

echo ">>>>>>>>running test 457"
../source/grep.exe "if a\+gout\b" ../inputs/grep*.dat  > ../outputs/t457 2>&1

echo ">>>>>>>>running test 458"
../source/grep.exe -G "\bif (\{1\}g\|if (""\{1\}out\b" ../inputs/grep*.dat  > ../outputs/t458 2>&1

echo ">>>>>>>>running test 459"
../source/grep.exe -G "\bif (\{1\}g\|\bif (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t459 2>&1

echo ">>>>>>>>running test 460"
../source/grep.exe -G "\(\bif (\{1\}g\|\bif (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t460 2>&1

echo ">>>>>>>>running test 461"
../source/grep.exe -G "\bif (\{1\}g\|\bif out" ../inputs/grep*.dat  > ../outputs/t461 2>&1

echo ">>>>>>>>running test 462"
../source/grep.exe "\bif (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t462 2>&1

echo ">>>>>>>>running test 463"
../source/grep.exe "\bif (\{1\}gout\b" ../inputs/grep*.dat  > ../outputs/t463 2>&1

echo ">>>>>>>>running test 464"
../source/grep.exe -G "\bif a\{1\}g\|if a""\{1\}out\b" ../inputs/grep*.dat  > ../outputs/t464 2>&1

echo ">>>>>>>>running test 465"
../source/grep.exe -G "\bif a\{1\}g\|\bif a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t465 2>&1

echo ">>>>>>>>running test 466"
../source/grep.exe -G "\(\bif a\{1\}g\|\bif a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t466 2>&1

echo ">>>>>>>>running test 467"
../source/grep.exe -G "if a\{1\}g\b\|\bif out" ../inputs/grep*.dat  > ../outputs/t467 2>&1

echo ">>>>>>>>running test 468"
../source/grep.exe -G "\bif a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t468 2>&1

echo ">>>>>>>>running test 469"
../source/grep.exe -G "if a\{1\}gout\b" ../inputs/grep*.dat  > ../outputs/t469 2>&1

echo ">>>>>>>>running test 470"
../source/grep.exe -Gc static ../inputs/grep*.dat  > ../outputs/t470 2>&1

