#!/bin/sh
#
# STImpL Test Script generated by 
# MakeTestScript on Nov 18, 2015 at 8:05:47 PM
# by the command: 
#  java sir.mts.MakeTestScript "--no-escapes" "--stimple-file" "../testplans/all
#  .universe" "--script-name" "vall.sh" "--experiment-dir" ".." "--exe-name" "..
#  /source/grep.exe" "--target" "bsh" "--print-config"

echo ">>>>>>>>running test 1"
../source/grep.exe -n I ../inputs/grep1.dat  > ../outputs/t1 2>&1

echo ">>>>>>>>running test 2"
../source/grep.exe -n 1 ../inputs/grep1.dat  > ../outputs/t2 2>&1

echo ">>>>>>>>running test 3"
../source/grep.exe -E '\?' ../inputs/grep1.dat  > ../outputs/t3 2>&1

echo ">>>>>>>>running test 4"
../source/grep.exe -G '\?' ../inputs/grep1.dat  > ../outputs/t4 2>&1

echo ">>>>>>>>running test 5"
../source/grep.exe -G '?' ../inputs/grep1.dat  > ../outputs/t5 2>&1

echo ">>>>>>>>running test 6"
../source/grep.exe -F '?' ../inputs/grep1.dat  > ../outputs/t6 2>&1

echo ">>>>>>>>running test 7"
../source/grep.exe -F '/*#include' ../inputs/grep1.dat  > ../outputs/t7 2>&1

echo ">>>>>>>>running test 8"
../source/grep.exe -G '[1-5]' ../inputs/grep1.dat  > ../outputs/t8 2>&1

echo ">>>>>>>>running test 9"
../source/grep.exe -E -c '[^a-z]' ../inputs/grep1.dat  > ../outputs/t9 2>&1

echo ">>>>>>>>running test 10"
../source/grep.exe -G '[X^YZ]' ../inputs/grep1.dat  > ../outputs/t10 2>&1

echo ">>>>>>>>running test 11"
../source/grep.exe -E '[1-]' ../inputs/grep1.dat  > ../outputs/t11 2>&1

echo ">>>>>>>>running test 12"
../source/grep.exe -G '\w' ../inputs/grep1.dat  > ../outputs/t12 2>&1

echo ">>>>>>>>running test 13"
../source/grep.exe -G '[[:alpha:]]' ../inputs/grep1.dat  > ../outputs/t13 2>&1

echo ">>>>>>>>running test 14"
../source/grep.exe -E "[[:cntrl:]]" ../inputs/grep1.dat  > ../outputs/t14 2>&1

echo ">>>>>>>>running test 15"
../source/grep.exe -E "[[:digit:]]" ../inputs/grep1.dat  > ../outputs/t15 2>&1

echo ">>>>>>>>running test 16"
../source/grep.exe -E "[[:graph:]]" ../inputs/grep1.dat  > ../outputs/t16 2>&1

echo ">>>>>>>>running test 17"
../source/grep.exe -G "[[:lower:]]" ../inputs/grep1.dat  > ../outputs/t17 2>&1

echo ">>>>>>>>running test 18"
../source/grep.exe -G "[[:print:]]" ../inputs/grep1.dat  > ../outputs/t18 2>&1

echo ">>>>>>>>running test 19"
../source/grep.exe -G '[[:punct:]]' ../inputs/grep1.dat  > ../outputs/t19 2>&1

echo ">>>>>>>>running test 20"
../source/grep.exe -G '[[:space:]]' ../inputs/grep1.dat  > ../outputs/t20 2>&1

echo ">>>>>>>>running test 21"
../source/grep.exe -G '[[:upper:]]' ../inputs/grep1.dat  > ../outputs/t21 2>&1

echo ">>>>>>>>running test 22"
../source/grep.exe -E '[[:xdigit:]]' ../inputs/grep1.dat  > ../outputs/t22 2>&1

echo ">>>>>>>>running test 23"
../source/grep.exe -E . ../inputs/grep1.dat  > ../outputs/t23 2>&1

echo ">>>>>>>>running test 24"
../source/grep.exe -E 'b$' ../inputs/grep1.dat  > ../outputs/t24 2>&1

echo ">>>>>>>>running test 25"
../source/grep.exe -E 'b\>' ../inputs/grep1.dat  > ../outputs/t25 2>&1

echo ">>>>>>>>running test 26"
../source/grep.exe -E 'b\B' ../inputs/grep1.dat  > ../outputs/t26 2>&1

echo ">>>>>>>>running test 27"
../source/grep.exe -E 'b*' ../inputs/grep1.dat  > ../outputs/t27 2>&1

echo ">>>>>>>>running test 28"
../source/grep.exe -E 'a{2,}' ../inputs/grep1.dat  > ../outputs/t28 2>&1

echo ">>>>>>>>running test 29"
../source/grep.exe -E 'a{,3}' ../inputs/grep1.dat  > ../outputs/t29 2>&1

echo ">>>>>>>>running test 30"
../source/grep.exe -E 'a{1,5}' ../inputs/grep1.dat  > ../outputs/t30 2>&1

echo ">>>>>>>>running test 31"
../source/grep.exe -E 'dfaanalyze|ab''[lo]' ../inputs/grep*.dat  > ../outputs/t31 2>&1

echo ">>>>>>>>running test 32"
../source/grep.exe -E '[ab]|include' ../inputs/grep*.dat  > ../outputs/t32 2>&1

echo ">>>>>>>>running test 33"
../source/grep.exe -E '[ab]''le' ../inputs/grep*.dat  > ../outputs/t33 2>&1

echo ">>>>>>>>running test 34"
../source/grep.exe -E '[12]' ../inputs/grep*.dat  > ../outputs/t34 2>&1

echo ">>>>>>>>running test 35"
../source/grep.exe -E 'include|\W''reg' ../inputs/grep*.dat  > ../outputs/t35 2>&1

echo ">>>>>>>>running test 36"
../source/grep.exe -E '[^[:alnum:]]|include' ../inputs/grep*.dat  > ../outputs/t36 2>&1

echo ">>>>>>>>running test 37"
../source/grep.exe -E '[^[:alnum:]]''include' ../inputs/grep*.dat  > ../outputs/t37 2>&1

echo ">>>>>>>>running test 38"
../source/grep.exe -E '[^[:alnum:]]' ../inputs/grep*.dat  > ../outputs/t38 2>&1

echo ">>>>>>>>running test 39"
../source/grep.exe -E 'In.lude|\?''?%' ../inputs/grep*.dat  > ../outputs/t39 2>&1

echo ">>>>>>>>running test 40"
../source/grep.exe -E 'in.lude|\??''%' ../inputs/grep*.dat  > ../outputs/t40 2>&1

echo ">>>>>>>>running test 41"
../source/grep.exe -E 'In.lude|\?(?''%)' ../inputs/grep*.dat  > ../outputs/t41 2>&1

echo ">>>>>>>>running test 42"
../source/grep.exe -Ec 'In.lude|\??' ../inputs/grep*.dat  > ../outputs/t42 2>&1

echo ">>>>>>>>running test 43"
../source/grep.exe -E '\?''?.:' ../inputs/grep*.dat  > ../outputs/t43 2>&1

echo ">>>>>>>>running test 44"
../source/grep.exe -E '\*(?''p.)' ../inputs/grep*.dat  > ../outputs/t44 2>&1

echo ">>>>>>>>running test 45"
../source/grep.exe -E '\*?p.eg' ../inputs/grep*.dat  > ../outputs/t45 2>&1

echo ">>>>>>>>running test 46"
../source/grep.exe -E 'Include|n''?.lud' ../inputs/grep*.dat  > ../outputs/t46 2>&1

echo ">>>>>>>>running test 47"
../source/grep.exe -E 'main|n?''.lud' ../inputs/grep*.dat  > ../outputs/t47 2>&1

echo ">>>>>>>>running test 48"
../source/grep.exe -E 'Include|n(?''.lud)' ../inputs/grep*.dat  > ../outputs/t48 2>&1

echo ">>>>>>>>running test 49"
../source/grep.exe -E 'Include|n?.lude' ../inputs/grep*.dat  > ../outputs/t49 2>&1

echo ">>>>>>>>running test 50"
../source/grep.exe -E 'n''?.lude' ../inputs/grep*.dat  > ../outputs/t50 2>&1

echo ">>>>>>>>running test 51"
../source/grep.exe -E 'n(?''.lud)' ../inputs/grep*.dat  > ../outputs/t51 2>&1

echo ">>>>>>>>running test 52"
../source/grep.exe -E 'n?.lud' ../inputs/grep*.dat  > ../outputs/t52 2>&1

echo ">>>>>>>>running test 53"
../source/grep.exe -E 'In.lude|\?''+%' ../inputs/grep*.dat  > ../outputs/t53 2>&1

echo ">>>>>>>>running test 54"
../source/grep.exe -E 'in.lude|\?+''%' ../inputs/grep*.dat  > ../outputs/t54 2>&1

echo ">>>>>>>>running test 55"
../source/grep.exe -E 'In.lude|\?(+''%)' ../inputs/grep*.dat  > ../outputs/t55 2>&1

echo ">>>>>>>>running test 56"
../source/grep.exe -Ec 'In.lude|\?+' ../inputs/grep*.dat  > ../outputs/t56 2>&1

echo ">>>>>>>>running test 57"
../source/grep.exe -E '\?''+.:' ../inputs/grep*.dat  > ../outputs/t57 2>&1

echo ">>>>>>>>running test 58"
../source/grep.exe -E '\*(+''p.)' ../inputs/grep*.dat  > ../outputs/t58 2>&1

echo ">>>>>>>>running test 59"
../source/grep.exe -E '\*+p.eg' ../inputs/grep*.dat  > ../outputs/t59 2>&1

echo ">>>>>>>>running test 60"
../source/grep.exe -E 'Include|n''+.lud' ../inputs/grep*.dat  > ../outputs/t60 2>&1

echo ">>>>>>>>running test 61"
../source/grep.exe -E 'Include|n+''.lud' ../inputs/grep*.dat  > ../outputs/t61 2>&1

echo ">>>>>>>>running test 62"
../source/grep.exe -E 'Include|n(+''.lud)' ../inputs/grep*.dat  > ../outputs/t62 2>&1

echo ">>>>>>>>running test 63"
../source/grep.exe -E 'Include|n+.lude' ../inputs/grep*.dat  > ../outputs/t63 2>&1

echo ">>>>>>>>running test 64"
../source/grep.exe -E 'n''+.lude' ../inputs/grep*.dat  > ../outputs/t64 2>&1

echo ">>>>>>>>running test 65"
../source/grep.exe -E 'n(+''.lud)' ../inputs/grep*.dat  > ../outputs/t65 2>&1

echo ">>>>>>>>running test 66"
../source/grep.exe -E 'n+.lud' ../inputs/grep*.dat  > ../outputs/t66 2>&1

echo ">>>>>>>>running test 67"
../source/grep.exe -E 'In.lude|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t67 2>&1

echo ">>>>>>>>running test 68"
../source/grep.exe -E 'in.lude|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t68 2>&1

echo ">>>>>>>>running test 69"
../source/grep.exe -E 'In.lude|\?({1}''%)' ../inputs/grep*.dat  > ../outputs/t69 2>&1

echo ">>>>>>>>running test 70"
../source/grep.exe -Ec 'In.lude|\?{1}' ../inputs/grep*.dat  > ../outputs/t70 2>&1

echo ">>>>>>>>running test 71"
../source/grep.exe -E '\?''{1}.:' ../inputs/grep*.dat  > ../outputs/t71 2>&1

echo ">>>>>>>>running test 72"
../source/grep.exe -E '\*({1}''p.)' ../inputs/grep*.dat  > ../outputs/t72 2>&1

echo ">>>>>>>>running test 73"
../source/grep.exe -E '\*{1}p.eg' ../inputs/grep*.dat  > ../outputs/t73 2>&1

echo ">>>>>>>>running test 74"
../source/grep.exe -E 'Include|n''{1}.lud' ../inputs/grep*.dat  > ../outputs/t74 2>&1

echo ">>>>>>>>running test 75"
../source/grep.exe -E 'Include|n{1}''.lud' ../inputs/grep*.dat  > ../outputs/t75 2>&1

echo ">>>>>>>>running test 76"
../source/grep.exe -E 'Include|n({1}''.lud)' ../inputs/grep*.dat  > ../outputs/t76 2>&1

echo ">>>>>>>>running test 77"
../source/grep.exe -E 'Include|n{1}.lude' ../inputs/grep*.dat  > ../outputs/t77 2>&1

echo ">>>>>>>>running test 78"
../source/grep.exe -E 'n''{1}.lude' ../inputs/grep*.dat  > ../outputs/t78 2>&1

echo ">>>>>>>>running test 79"
../source/grep.exe -E 'n({1}''.lud)' ../inputs/grep*.dat  > ../outputs/t79 2>&1

echo ">>>>>>>>running test 80"
../source/grep.exe -E 'n{1}.lud' ../inputs/grep*.dat  > ../outputs/t80 2>&1

echo ">>>>>>>>running test 81"
../source/grep.exe -E 'In.lude|\?''%' ../inputs/grep*.dat  > ../outputs/t81 2>&1

echo ">>>>>>>>running test 82"
../source/grep.exe -Ec 'In.lude|\?' ../inputs/grep*.dat  > ../outputs/t82 2>&1

echo ">>>>>>>>running test 83"
../source/grep.exe -E '\*\*''p.' ../inputs/grep*.dat  > ../outputs/t83 2>&1

echo ">>>>>>>>running test 84"
../source/grep.exe -E '\*p.eg' ../inputs/grep*.dat  > ../outputs/t84 2>&1

echo ">>>>>>>>running test 85"
../source/grep.exe -E 'Include|\?''?%' ../inputs/grep*.dat  > ../outputs/t85 2>&1

echo ">>>>>>>>running test 86"
../source/grep.exe -E 'include|\?''?%' ../inputs/grep*.dat  > ../outputs/t86 2>&1

echo ">>>>>>>>running test 87"
../source/grep.exe -E 'Include|\?(?''%)' ../inputs/grep*.dat  > ../outputs/t87 2>&1

echo ">>>>>>>>running test 88"
../source/grep.exe -Ec 'Include|\??' ../inputs/grep*.dat  > ../outputs/t88 2>&1

echo ">>>>>>>>running test 89"
../source/grep.exe -E '\?''? :' ../inputs/grep*.dat  > ../outputs/t89 2>&1

echo ">>>>>>>>running test 90"
../source/grep.exe -E '\*(?''p)' ../inputs/grep*.dat  > ../outputs/t90 2>&1

echo ">>>>>>>>running test 91"
../source/grep.exe -E '\*?preg' ../inputs/grep*.dat  > ../outputs/t91 2>&1

echo ">>>>>>>>running test 92"
../source/grep.exe -E 'Include|n''?clud' ../inputs/grep*.dat  > ../outputs/t92 2>&1

echo ">>>>>>>>running test 93"
../source/grep.exe -E 'main|in?''clude' ../inputs/grep*.dat  > ../outputs/t93 2>&1

echo ">>>>>>>>running test 94"
../source/grep.exe -E 'Include|n(?''clud)' ../inputs/grep*.dat  > ../outputs/t94 2>&1

echo ">>>>>>>>running test 95"
../source/grep.exe -E 'main|n?clude' ../inputs/grep*.dat  > ../outputs/t95 2>&1

echo ">>>>>>>>running test 96"
../source/grep.exe -E 'n''?clude' ../inputs/grep*.dat  > ../outputs/t96 2>&1

echo ">>>>>>>>running test 97"
../source/grep.exe -E 'n(?''clud)' ../inputs/grep*.dat  > ../outputs/t97 2>&1

echo ">>>>>>>>running test 98"
../source/grep.exe -E 'n?clud' ../inputs/grep*.dat  > ../outputs/t98 2>&1

echo ">>>>>>>>running test 99"
../source/grep.exe -E 'Include|\?''+%' ../inputs/grep*.dat  > ../outputs/t99 2>&1

echo ">>>>>>>>running test 100"
../source/grep.exe -E 'include|\?''+%' ../inputs/grep*.dat  > ../outputs/t100 2>&1

echo ">>>>>>>>running test 101"
../source/grep.exe -E 'Include|\?(+''%)' ../inputs/grep*.dat  > ../outputs/t101 2>&1

echo ">>>>>>>>running test 102"
../source/grep.exe -Ec 'Include|\?+' ../inputs/grep*.dat  > ../outputs/t102 2>&1

echo ">>>>>>>>running test 103"
../source/grep.exe -E '\?''+ 0' ../inputs/grep*.dat  > ../outputs/t103 2>&1

echo ">>>>>>>>running test 104"
../source/grep.exe -E '\*(+''pattern)' ../inputs/grep*.dat  > ../outputs/t104 2>&1

echo ">>>>>>>>running test 105"
../source/grep.exe -E '\*+preg' ../inputs/grep*.dat  > ../outputs/t105 2>&1

echo ">>>>>>>>running test 106"
../source/grep.exe -E 'main|n''+clud' ../inputs/grep*.dat  > ../outputs/t106 2>&1

echo ">>>>>>>>running test 107"
../source/grep.exe -E 'Include|n+''clud' ../inputs/grep*.dat  > ../outputs/t107 2>&1

echo ">>>>>>>>running test 108"
../source/grep.exe -E 'Include|n(+''clud)' ../inputs/grep*.dat  > ../outputs/t108 2>&1

echo ">>>>>>>>running test 109"
../source/grep.exe -E 'Include|n+clude' ../inputs/grep*.dat  > ../outputs/t109 2>&1

echo ">>>>>>>>running test 110"
../source/grep.exe -E 'n''+clude' ../inputs/grep*.dat  > ../outputs/t110 2>&1

echo ">>>>>>>>running test 111"
../source/grep.exe -E 'n(+''clud)' ../inputs/grep*.dat  > ../outputs/t111 2>&1

echo ">>>>>>>>running test 112"
../source/grep.exe -E 'n+clud' ../inputs/grep*.dat  > ../outputs/t112 2>&1

echo ">>>>>>>>running test 113"
../source/grep.exe -E 'Include|\?''{1}%' ../inputs/grep*.dat  > ../outputs/t113 2>&1

echo ">>>>>>>>running test 114"
../source/grep.exe -E 'include|\?{1}''%' ../inputs/grep*.dat  > ../outputs/t114 2>&1

echo ">>>>>>>>running test 115"
../source/grep.exe -E 'Include|\?({1}''%)' ../inputs/grep*.dat  > ../outputs/t115 2>&1

echo ">>>>>>>>running test 116"
../source/grep.exe -Ec 'Include|\?{1}' ../inputs/grep*.dat  > ../outputs/t116 2>&1

echo ">>>>>>>>running test 117"
../source/grep.exe -E '\?''{1} 0' ../inputs/grep*.dat  > ../outputs/t117 2>&1

echo ">>>>>>>>running test 118"
../source/grep.exe -E '\*({1}''pr)' ../inputs/grep*.dat  > ../outputs/t118 2>&1

echo ">>>>>>>>running test 119"
../source/grep.exe -E '\*{1}preg' ../inputs/grep*.dat  > ../outputs/t119 2>&1

echo ">>>>>>>>running test 120"
../source/grep.exe -E 'Include|n''{1}clud' ../inputs/grep*.dat  > ../outputs/t120 2>&1

echo ">>>>>>>>running test 121"
../source/grep.exe -E 'main|n{1}''clud' ../inputs/grep*.dat  > ../outputs/t121 2>&1

echo ">>>>>>>>running test 122"
../source/grep.exe -E 'Include|n({1}''clud)' ../inputs/grep*.dat  > ../outputs/t122 2>&1

echo ">>>>>>>>running test 123"
../source/grep.exe -E 'Include|n{1}clude' ../inputs/grep*.dat  > ../outputs/t123 2>&1

echo ">>>>>>>>running test 124"
../source/grep.exe -E 'n''{1}clude' ../inputs/grep*.dat  > ../outputs/t124 2>&1

echo ">>>>>>>>running test 125"
../source/grep.exe -E 'n({1}''clud)' ../inputs/grep*.dat  > ../outputs/t125 2>&1

echo ">>>>>>>>running test 126"
../source/grep.exe -E 'n{1}clud' ../inputs/grep*.dat  > ../outputs/t126 2>&1

echo ">>>>>>>>running test 127"
../source/grep.exe -E 'Include|\?''%' ../inputs/grep*.dat  > ../outputs/t127 2>&1

echo ">>>>>>>>running test 128"
../source/grep.exe -Ec 'Include|\?' ../inputs/grep*.dat  > ../outputs/t128 2>&1

echo ">>>>>>>>running test 129"
../source/grep.exe -E 'static'' int' ../inputs/grep*.dat  > ../outputs/t129 2>&1

echo ">>>>>>>>running test 130"
../source/grep.exe -E '\*preg' ../inputs/grep*.dat  > ../outputs/t130 2>&1

echo ">>>>>>>>running test 131"
../source/grep.exe -E "[]X]|end"" -" ../inputs/grep*.dat  > ../outputs/t131 2>&1

echo ">>>>>>>>running test 132"
../source/grep.exe -E "[]X]|end" ../inputs/grep*.dat  > ../outputs/t132 2>&1

echo ">>>>>>>>running test 133"
../source/grep.exe -E "[]X]"" -" ../inputs/grep*.dat  > ../outputs/t133 2>&1

echo ">>>>>>>>running test 134"
../source/grep.exe -E "[]X]" ../inputs/grep*.dat  > ../outputs/t134 2>&1

echo ">>>>>>>>running test 135"
../source/grep.exe -E "^if \(?g|if \(""?out" ../inputs/grep*.dat  > ../outputs/t135 2>&1

echo ">>>>>>>>running test 136"
../source/grep.exe -E "^if \(?g|^if \(?""out" ../inputs/grep*.dat  > ../outputs/t136 2>&1

echo ">>>>>>>>running test 137"
../source/grep.exe -E "^if \(?g|^if \((?""out)" ../inputs/grep*.dat  > ../outputs/t137 2>&1

echo ">>>>>>>>running test 138"
../source/grep.exe -E "^if \(?g|^if out" ../inputs/grep*.dat  > ../outputs/t138 2>&1

echo ">>>>>>>>running test 139"
../source/grep.exe -E "^if \(""?gout" ../inputs/grep*.dat  > ../outputs/t139 2>&1

echo ">>>>>>>>running test 140"
../source/grep.exe -E "^if \((?""gout)" ../inputs/grep*.dat  > ../outputs/t140 2>&1

echo ">>>>>>>>running test 141"
../source/grep.exe -E "^if \(?gout" ../inputs/grep*.dat  > ../outputs/t141 2>&1

echo ">>>>>>>>running test 142"
../source/grep.exe -E "^if a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t142 2>&1

echo ">>>>>>>>running test 143"
../source/grep.exe -E "^if a?g|^if a?""out" ../inputs/grep*.dat  > ../outputs/t143 2>&1

echo ">>>>>>>>running test 144"
../source/grep.exe -E "^if a?g|^if a(?""out)" ../inputs/grep*.dat  > ../outputs/t144 2>&1

echo ">>>>>>>>running test 145"
../source/grep.exe -E "^if a?g|^if out" ../inputs/grep*.dat  > ../outputs/t145 2>&1

echo ">>>>>>>>running test 146"
../source/grep.exe -E "^if a""?gout" ../inputs/grep*.dat  > ../outputs/t146 2>&1

echo ">>>>>>>>running test 147"
../source/grep.exe -E "^if a(?""gout)" ../inputs/grep*.dat  > ../outputs/t147 2>&1

echo ">>>>>>>>running test 148"
../source/grep.exe -E "^if a?gout" ../inputs/grep*.dat  > ../outputs/t148 2>&1

echo ">>>>>>>>running test 149"
../source/grep.exe -E "^if \(+g|if \(""+out" ../inputs/grep*.dat  > ../outputs/t149 2>&1

echo ">>>>>>>>running test 150"
../source/grep.exe -E "^if \(+g|^if \(+""out" ../inputs/grep*.dat  > ../outputs/t150 2>&1

echo ">>>>>>>>running test 151"
../source/grep.exe -E "^if \(+g|^if \((+""out)" ../inputs/grep*.dat  > ../outputs/t151 2>&1

echo ">>>>>>>>running test 152"
../source/grep.exe -E "^if \(+g|^if out" ../inputs/grep*.dat  > ../outputs/t152 2>&1

echo ">>>>>>>>running test 153"
../source/grep.exe -E "^if \(""+gout" ../inputs/grep*.dat  > ../outputs/t153 2>&1

echo ">>>>>>>>running test 154"
../source/grep.exe -E "^if \((+""gout)" ../inputs/grep*.dat  > ../outputs/t154 2>&1

echo ">>>>>>>>running test 155"
../source/grep.exe -E "^if \(+gout" ../inputs/grep*.dat  > ../outputs/t155 2>&1

echo ">>>>>>>>running test 156"
../source/grep.exe -E "^if a+g|if a""+out" ../inputs/grep*.dat  > ../outputs/t156 2>&1

echo ">>>>>>>>running test 157"
../source/grep.exe -E "^if a+g|^if a+""out" ../inputs/grep*.dat  > ../outputs/t157 2>&1

echo ">>>>>>>>running test 158"
../source/grep.exe -E "^if a+g|^if a(+""out)" ../inputs/grep*.dat  > ../outputs/t158 2>&1

echo ">>>>>>>>running test 159"
../source/grep.exe -E "^if a+g|^if out" ../inputs/grep*.dat  > ../outputs/t159 2>&1

echo ">>>>>>>>running test 160"
../source/grep.exe -E "^if a""+gout" ../inputs/grep*.dat  > ../outputs/t160 2>&1

echo ">>>>>>>>running test 161"
../source/grep.exe -E "^if a(+""gout)" ../inputs/grep*.dat  > ../outputs/t161 2>&1

echo ">>>>>>>>running test 162"
../source/grep.exe -E "^if a+gout" ../inputs/grep*.dat  > ../outputs/t162 2>&1

echo ">>>>>>>>running test 163"
../source/grep.exe -E "^if \({1}g|if \(""{1}out" ../inputs/grep*.dat  > ../outputs/t163 2>&1

echo ">>>>>>>>running test 164"
../source/grep.exe -E "^if \({1}g|^if \({1}""out" ../inputs/grep*.dat  > ../outputs/t164 2>&1

echo ">>>>>>>>running test 165"
../source/grep.exe -E "^if \({1}g|^if \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t165 2>&1

echo ">>>>>>>>running test 166"
../source/grep.exe -E "^if \({1}g|^if out" ../inputs/grep*.dat  > ../outputs/t166 2>&1

echo ">>>>>>>>running test 167"
../source/grep.exe -E "^if \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t167 2>&1

echo ">>>>>>>>running test 168"
../source/grep.exe -E "^if \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t168 2>&1

echo ">>>>>>>>running test 169"
../source/grep.exe -E "^if \({1}gout" ../inputs/grep*.dat  > ../outputs/t169 2>&1

echo ">>>>>>>>running test 170"
../source/grep.exe -E "^if a{1}g|if a""{1}out" ../inputs/grep*.dat  > ../outputs/t170 2>&1

echo ">>>>>>>>running test 171"
../source/grep.exe -E "^if a{1}g|^if a{1}""out" ../inputs/grep*.dat  > ../outputs/t171 2>&1

echo ">>>>>>>>running test 172"
../source/grep.exe -E "^if a{1}g|^if a({1}""out)" ../inputs/grep*.dat  > ../outputs/t172 2>&1

echo ">>>>>>>>running test 173"
../source/grep.exe -E "^if a{1}g|^if out" ../inputs/grep*.dat  > ../outputs/t173 2>&1

echo ">>>>>>>>running test 174"
../source/grep.exe -E "^if a""{1}gout" ../inputs/grep*.dat  > ../outputs/t174 2>&1

echo ">>>>>>>>running test 175"
../source/grep.exe -E "^if a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t175 2>&1

echo ">>>>>>>>running test 176"
../source/grep.exe -E "^if a{1}gout" ../inputs/grep*.dat  > ../outputs/t176 2>&1

echo ">>>>>>>>running test 177"
../source/grep.exe -E "\<if \(?g|if \(""?out" ../inputs/grep*.dat  > ../outputs/t177 2>&1

echo ">>>>>>>>running test 178"
../source/grep.exe -E "\<if \(?g|\<if \(?""out" ../inputs/grep*.dat  > ../outputs/t178 2>&1

echo ">>>>>>>>running test 179"
../source/grep.exe -E "\<if \(?g|\<if \((?""out)" ../inputs/grep*.dat  > ../outputs/t179 2>&1

echo ">>>>>>>>running test 180"
../source/grep.exe -E "\<if \(?g|\<if out" ../inputs/grep*.dat  > ../outputs/t180 2>&1

echo ">>>>>>>>running test 181"
../source/grep.exe -E "\<if \(""?gout" ../inputs/grep*.dat  > ../outputs/t181 2>&1

echo ">>>>>>>>running test 182"
../source/grep.exe -E "\<if \((?""gout)" ../inputs/grep*.dat  > ../outputs/t182 2>&1

echo ">>>>>>>>running test 183"
../source/grep.exe -E "\<if \(?gout" ../inputs/grep*.dat  > ../outputs/t183 2>&1

echo ">>>>>>>>running test 184"
../source/grep.exe -E "\<if a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t184 2>&1

echo ">>>>>>>>running test 185"
../source/grep.exe -E "\<if a?g|\<if a?""out" ../inputs/grep*.dat  > ../outputs/t185 2>&1

echo ">>>>>>>>running test 186"
../source/grep.exe -E "\<if a?g|\<if a(?""out)" ../inputs/grep*.dat  > ../outputs/t186 2>&1

echo ">>>>>>>>running test 187"
../source/grep.exe -E "\<if a?g|\<if out" ../inputs/grep*.dat  > ../outputs/t187 2>&1

echo ">>>>>>>>running test 188"
../source/grep.exe -E "\<if a""?gout" ../inputs/grep*.dat  > ../outputs/t188 2>&1

echo ">>>>>>>>running test 189"
../source/grep.exe -E "\<if a(?""gout)" ../inputs/grep*.dat  > ../outputs/t189 2>&1

echo ">>>>>>>>running test 190"
../source/grep.exe -E "\<if a?gout" ../inputs/grep*.dat  > ../outputs/t190 2>&1

echo ">>>>>>>>running test 191"
../source/grep.exe -E "\<if \(+g|if \(""+out" ../inputs/grep*.dat  > ../outputs/t191 2>&1

echo ">>>>>>>>running test 192"
../source/grep.exe -E "\<if \(+g|\<if \(+""out" ../inputs/grep*.dat  > ../outputs/t192 2>&1

echo ">>>>>>>>running test 193"
../source/grep.exe -E "\<if \(+g|\<if \((+""out)" ../inputs/grep*.dat  > ../outputs/t193 2>&1

echo ">>>>>>>>running test 194"
../source/grep.exe -E "\<if \(+g|\<if out" ../inputs/grep*.dat  > ../outputs/t194 2>&1

echo ">>>>>>>>running test 195"
../source/grep.exe -E "\<if \(""+gout" ../inputs/grep*.dat  > ../outputs/t195 2>&1

echo ">>>>>>>>running test 196"
../source/grep.exe -E "\<if \((+""gout)" ../inputs/grep*.dat  > ../outputs/t196 2>&1

echo ">>>>>>>>running test 197"
../source/grep.exe -E "\<if \(+gout" ../inputs/grep*.dat  > ../outputs/t197 2>&1

echo ">>>>>>>>running test 198"
../source/grep.exe -E "\<if a+g|if a""+out" ../inputs/grep*.dat  > ../outputs/t198 2>&1

echo ">>>>>>>>running test 199"
../source/grep.exe -E "\<if a+g|\<if a+""out" ../inputs/grep*.dat  > ../outputs/t199 2>&1

echo ">>>>>>>>running test 200"
../source/grep.exe -E "\<if a+g|\<if a(+""out)" ../inputs/grep*.dat  > ../outputs/t200 2>&1

echo ">>>>>>>>running test 201"
../source/grep.exe -E "\<if a+g|\<if out" ../inputs/grep*.dat  > ../outputs/t201 2>&1

echo ">>>>>>>>running test 202"
../source/grep.exe -E "\<if a""+gout" ../inputs/grep*.dat  > ../outputs/t202 2>&1

echo ">>>>>>>>running test 203"
../source/grep.exe -E "\<if a(+""gout)" ../inputs/grep*.dat  > ../outputs/t203 2>&1

echo ">>>>>>>>running test 204"
../source/grep.exe -E "\<if a+gout" ../inputs/grep*.dat  > ../outputs/t204 2>&1

echo ">>>>>>>>running test 205"
../source/grep.exe -E "\<if \({1}g|if \(""{1}out" ../inputs/grep*.dat  > ../outputs/t205 2>&1

echo ">>>>>>>>running test 206"
../source/grep.exe -E "\<if \({1}g|\<if \({1}""out" ../inputs/grep*.dat  > ../outputs/t206 2>&1

echo ">>>>>>>>running test 207"
../source/grep.exe -E "\<if \({1}g|\<if \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t207 2>&1

echo ">>>>>>>>running test 208"
../source/grep.exe -E "\<if \({1}g|\<if out" ../inputs/grep*.dat  > ../outputs/t208 2>&1

echo ">>>>>>>>running test 209"
../source/grep.exe -E "\<if \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t209 2>&1

echo ">>>>>>>>running test 210"
../source/grep.exe -E "\<if \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t210 2>&1

echo ">>>>>>>>running test 211"
../source/grep.exe -E "\<if \({1}gout" ../inputs/grep*.dat  > ../outputs/t211 2>&1

echo ">>>>>>>>running test 212"
../source/grep.exe -E "\<if a{1}g|if a""{1}out" ../inputs/grep*.dat  > ../outputs/t212 2>&1

echo ">>>>>>>>running test 213"
../source/grep.exe -E "\<if a{1}g|\<if a{1}""out" ../inputs/grep*.dat  > ../outputs/t213 2>&1

echo ">>>>>>>>running test 214"
../source/grep.exe -E "\<if a{1}g|\<if a({1}""out)" ../inputs/grep*.dat  > ../outputs/t214 2>&1

echo ">>>>>>>>running test 215"
../source/grep.exe -E "\<if a{1}g|\<if out" ../inputs/grep*.dat  > ../outputs/t215 2>&1

echo ">>>>>>>>running test 216"
../source/grep.exe -E "\<if a""{1}gout" ../inputs/grep*.dat  > ../outputs/t216 2>&1

echo ">>>>>>>>running test 217"
../source/grep.exe -E "\<if a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t217 2>&1

echo ">>>>>>>>running test 218"
../source/grep.exe -E "\<if a{1}gout" ../inputs/grep*.dat  > ../outputs/t218 2>&1

echo ">>>>>>>>running test 219"
../source/grep.exe -E "\bif \(?g|if \(""?out\b" ../inputs/grep*.dat  > ../outputs/t219 2>&1

echo ">>>>>>>>running test 220"
../source/grep.exe -E "\bif \(?g|\bif \(?""out" ../inputs/grep*.dat  > ../outputs/t220 2>&1

echo ">>>>>>>>running test 221"
../source/grep.exe -E "\bif \(?g\b|\bif \((?""out)" ../inputs/grep*.dat  > ../outputs/t221 2>&1

echo ">>>>>>>>running test 222"
../source/grep.exe -E "\bif \(?g\b|\bif out" ../inputs/grep*.dat  > ../outputs/t222 2>&1

echo ">>>>>>>>running test 223"
../source/grep.exe -E "\bif \(""?gout" ../inputs/grep*.dat  > ../outputs/t223 2>&1

echo ">>>>>>>>running test 224"
../source/grep.exe -E "\bif \((?""gout)" ../inputs/grep*.dat  > ../outputs/t224 2>&1

echo ">>>>>>>>running test 225"
../source/grep.exe -E "\bif \(?gout\b" ../inputs/grep*.dat  > ../outputs/t225 2>&1

echo ">>>>>>>>running test 226"
../source/grep.exe -E "\bif a?g|if a""?out" ../inputs/grep*.dat  > ../outputs/t226 2>&1

echo ">>>>>>>>running test 227"
../source/grep.exe -E "\bif a?g|\bif a?""out" ../inputs/grep*.dat  > ../outputs/t227 2>&1

echo ">>>>>>>>running test 228"
../source/grep.exe -E "\bif a?g|\bif a(?""out)" ../inputs/grep*.dat  > ../outputs/t228 2>&1

echo ">>>>>>>>running test 229"
../source/grep.exe -E "\bif a?g|\bif out\b" ../inputs/grep*.dat  > ../outputs/t229 2>&1

echo ">>>>>>>>running test 230"
../source/grep.exe -E "\bif a""?gout\b" ../inputs/grep*.dat  > ../outputs/t230 2>&1

echo ">>>>>>>>running test 231"
../source/grep.exe -E "\bif a(?""gout)" ../inputs/grep*.dat  > ../outputs/t231 2>&1

echo ">>>>>>>>running test 232"
../source/grep.exe -E "\bif a?gout" ../inputs/grep*.dat  > ../outputs/t232 2>&1

echo ">>>>>>>>running test 233"
../source/grep.exe -E "\bif \(+g\b|if \(""+out" ../inputs/grep*.dat  > ../outputs/t233 2>&1

echo ">>>>>>>>running test 234"
../source/grep.exe -E "\bif \(+g|\bif \(+""out" ../inputs/grep*.dat  > ../outputs/t234 2>&1

echo ">>>>>>>>running test 235"
../source/grep.exe -E "\bif \(+g|\bif \((+""out)" ../inputs/grep*.dat  > ../outputs/t235 2>&1

echo ">>>>>>>>running test 236"
../source/grep.exe -E "\bif \(+g|\bif out" ../inputs/grep*.dat  > ../outputs/t236 2>&1

echo ">>>>>>>>running test 237"
../source/grep.exe -E "\bif \(""+gout\b" ../inputs/grep*.dat  > ../outputs/t237 2>&1

echo ">>>>>>>>running test 238"
../source/grep.exe -E "\bif \((+""gout)" ../inputs/grep*.dat  > ../outputs/t238 2>&1

echo ">>>>>>>>running test 239"
../source/grep.exe -E "\bif \(+gout" ../inputs/grep*.dat  > ../outputs/t239 2>&1

echo ">>>>>>>>running test 240"
../source/grep.exe -E "\bif a+g\b|if a""+out" ../inputs/grep*.dat  > ../outputs/t240 2>&1

echo ">>>>>>>>running test 241"
../source/grep.exe -E "if a+g\b|\bif a+""out" ../inputs/grep*.dat  > ../outputs/t241 2>&1

echo ">>>>>>>>running test 242"
../source/grep.exe -E "\bif a+g|\bif a(+""out)" ../inputs/grep*.dat  > ../outputs/t242 2>&1

echo ">>>>>>>>running test 243"
../source/grep.exe -E "\bif a+g|\bif out" ../inputs/grep*.dat  > ../outputs/t243 2>&1

echo ">>>>>>>>running test 244"
../source/grep.exe -E "if a""+gout\b" ../inputs/grep*.dat  > ../outputs/t244 2>&1

echo ">>>>>>>>running test 245"
../source/grep.exe -E "\bif a(+""gout)" ../inputs/grep*.dat  > ../outputs/t245 2>&1

echo ">>>>>>>>running test 246"
../source/grep.exe -E "if a+gout\b" ../inputs/grep*.dat  > ../outputs/t246 2>&1

echo ">>>>>>>>running test 247"
../source/grep.exe -E "\bif \({1}g|if \(""{1}out\b" ../inputs/grep*.dat  > ../outputs/t247 2>&1

echo ">>>>>>>>running test 248"
../source/grep.exe -E "\bif \({1}g|\bif \({1}""out" ../inputs/grep*.dat  > ../outputs/t248 2>&1

echo ">>>>>>>>running test 249"
../source/grep.exe -E "if \({1}g\b|\bif \(({1}""out)" ../inputs/grep*.dat  > ../outputs/t249 2>&1

echo ">>>>>>>>running test 250"
../source/grep.exe -E "\bif \({1}g|\bif out" ../inputs/grep*.dat  > ../outputs/t250 2>&1

echo ">>>>>>>>running test 251"
../source/grep.exe -E "\bif \(""{1}gout" ../inputs/grep*.dat  > ../outputs/t251 2>&1

echo ">>>>>>>>running test 252"
../source/grep.exe -E "\bif \(({1}""gout)" ../inputs/grep*.dat  > ../outputs/t252 2>&1

echo ">>>>>>>>running test 253"
../source/grep.exe -E "\bif \({1}gout\b" ../inputs/grep*.dat  > ../outputs/t253 2>&1

echo ">>>>>>>>running test 254"
../source/grep.exe -E "\bif a{1}g|if a""{1}out\b" ../inputs/grep*.dat  > ../outputs/t254 2>&1

echo ">>>>>>>>running test 255"
../source/grep.exe -E "\bif a{1}g|\bif a{1}""out" ../inputs/grep*.dat  > ../outputs/t255 2>&1

echo ">>>>>>>>running test 256"
../source/grep.exe -E "\bif a{1}g|\bif a({1}""out)" ../inputs/grep*.dat  > ../outputs/t256 2>&1

echo ">>>>>>>>running test 257"
../source/grep.exe -E "if a{1}g\b|\bif out" ../inputs/grep*.dat  > ../outputs/t257 2>&1

echo ">>>>>>>>running test 258"
../source/grep.exe -E "\bif a""{1}gout" ../inputs/grep*.dat  > ../outputs/t258 2>&1

echo ">>>>>>>>running test 259"
../source/grep.exe -E "\bif a({1}""gout)" ../inputs/grep*.dat  > ../outputs/t259 2>&1

echo ">>>>>>>>running test 260"
../source/grep.exe -E "if a{1}gout\b" ../inputs/grep*.dat  > ../outputs/t260 2>&1

echo ">>>>>>>>running test 261"
../source/grep.exe -Ec static ../inputs/grep*.dat  > ../outputs/t261 2>&1

echo ">>>>>>>>running test 262"
../source/grep.exe -F 'if (out)' ../inputs/grep*.dat  > ../outputs/t262 2>&1

echo ">>>>>>>>running test 263"
../source/grep.exe -F "if (gout)" ../inputs/grep*.dat  > ../outputs/t263 2>&1

echo ">>>>>>>>running test 264"
../source/grep.exe -F agout ../inputs/grep*.dat  > ../outputs/t264 2>&1

echo ">>>>>>>>running test 265"
../source/grep.exe -G 'dfaanalyze\|ab''[lo]' ../inputs/grep*.dat  > ../outputs/t265 2>&1

echo ">>>>>>>>running test 266"
../source/grep.exe -G '\(dfaanalyze\|ab\)''[lo]' ../inputs/grep*.dat  > ../outputs/t266 2>&1

echo ">>>>>>>>running test 267"
../source/grep.exe -G '[ab]\|include' ../inputs/grep*.dat  > ../outputs/t267 2>&1

echo ">>>>>>>>running test 268"
../source/grep.exe '[ab]''le' ../inputs/grep*.dat  > ../outputs/t268 2>&1

echo ">>>>>>>>running test 269"
../source/grep.exe -G '[12]' ../inputs/grep*.dat  > ../outputs/t269 2>&1

echo ">>>>>>>>running test 270"
../source/grep.exe -G 'include\|\W''reg' ../inputs/grep*.dat  > ../outputs/t270 2>&1

echo ">>>>>>>>running test 271"
../source/grep.exe -G '\(include\|\W\)''reg' ../inputs/grep*.dat  > ../outputs/t271 2>&1

echo ">>>>>>>>running test 272"
../source/grep.exe '[^[:alnum:]]\|include' ../inputs/grep*.dat  > ../outputs/t272 2>&1

echo ">>>>>>>>running test 273"
../source/grep.exe -G '[^[:alnum:]]''include' ../inputs/grep*.dat  > ../outputs/t273 2>&1

echo ">>>>>>>>running test 274"
../source/grep.exe -G '[^[:alnum:]]' ../inputs/grep*.dat  > ../outputs/t274 2>&1

echo ">>>>>>>>running test 275"
../source/grep.exe -G 'In.lude\|?''\?%' ../inputs/grep*.dat  > ../outputs/t275 2>&1

echo ">>>>>>>>running test 276"
../source/grep.exe -G 'in.lude\|?\?''%' ../inputs/grep*.dat  > ../outputs/t276 2>&1

echo ">>>>>>>>running test 277"
../source/grep.exe -G '\(in.lude\|?\?\)''%' ../inputs/grep*.dat  > ../outputs/t277 2>&1

echo ">>>>>>>>running test 278"
../source/grep.exe -Gc 'In.lude\|?\?' ../inputs/grep*.dat  > ../outputs/t278 2>&1

echo ">>>>>>>>running test 279"
../source/grep.exe -G '?''\?.:' ../inputs/grep*.dat  > ../outputs/t279 2>&1

echo ">>>>>>>>running test 280"
../source/grep.exe -G '\*\?p.eg' ../inputs/grep*.dat  > ../outputs/t280 2>&1

echo ">>>>>>>>running test 281"
../source/grep.exe -G 'Include\|n''\?.lud' ../inputs/grep*.dat  > ../outputs/t281 2>&1

echo ">>>>>>>>running test 282"
../source/grep.exe -G 'main\|n\?''.lud' ../inputs/grep*.dat  > ../outputs/t282 2>&1

echo ">>>>>>>>running test 283"
../source/grep.exe -G '\(main\|n\?\)''.lud' ../inputs/grep*.dat  > ../outputs/t283 2>&1

echo ">>>>>>>>running test 284"
../source/grep.exe 'Include\|n\?.lude' ../inputs/grep*.dat  > ../outputs/t284 2>&1

echo ">>>>>>>>running test 285"
../source/grep.exe -G 'n''\?.lude' ../inputs/grep*.dat  > ../outputs/t285 2>&1

echo ">>>>>>>>running test 286"
../source/grep.exe -G 'n\?.lud' ../inputs/grep*.dat  > ../outputs/t286 2>&1

echo ">>>>>>>>running test 287"
../source/grep.exe -G 'In.lude\|?''\+%' ../inputs/grep*.dat  > ../outputs/t287 2>&1

echo ">>>>>>>>running test 288"
../source/grep.exe -G 'in.lude\|?\+''%' ../inputs/grep*.dat  > ../outputs/t288 2>&1

echo ">>>>>>>>running test 289"
../source/grep.exe -G '\(in.lude\|?\+\)''%' ../inputs/grep*.dat  > ../outputs/t289 2>&1

echo ">>>>>>>>running test 290"
../source/grep.exe -Gc 'In.lude\|?\+' ../inputs/grep*.dat  > ../outputs/t290 2>&1

echo ">>>>>>>>running test 291"
../source/grep.exe -G '?''\+.:' ../inputs/grep*.dat  > ../outputs/t291 2>&1

echo ">>>>>>>>running test 292"
../source/grep.exe '\*\+p.eg' ../inputs/grep*.dat  > ../outputs/t292 2>&1

echo ">>>>>>>>running test 293"
../source/grep.exe -G 'Include\|n''\+.lud' ../inputs/grep*.dat  > ../outputs/t293 2>&1

echo ">>>>>>>>running test 294"
../source/grep.exe -G 'Include\|n\+''.lud' ../inputs/grep*.dat  > ../outputs/t294 2>&1

echo ">>>>>>>>running test 295"
../source/grep.exe -G '\(Include\|n\+\)''.lud' ../inputs/grep*.dat  > ../outputs/t295 2>&1

echo ">>>>>>>>running test 296"
../source/grep.exe -G 'Include\|n\+.lude' ../inputs/grep*.dat  > ../outputs/t296 2>&1

echo ">>>>>>>>running test 297"
../source/grep.exe 'n''\+.lude' ../inputs/grep*.dat  > ../outputs/t297 2>&1

echo ">>>>>>>>running test 298"
../source/grep.exe 'n\+.lud' ../inputs/grep*.dat  > ../outputs/t298 2>&1

echo ">>>>>>>>running test 299"
../source/grep.exe -G 'In.lude\|?''\{1\}%' ../inputs/grep*.dat  > ../outputs/t299 2>&1

echo ">>>>>>>>running test 300"
../source/grep.exe -G 'in.lude\|?\{1\}''%' ../inputs/grep*.dat  > ../outputs/t300 2>&1

echo ">>>>>>>>running test 301"
../source/grep.exe -G '\(in.lude\|?\{1\}\)''%' ../inputs/grep*.dat  > ../outputs/t301 2>&1

echo ">>>>>>>>running test 302"
../source/grep.exe -c 'In.lude\|?\{1\}' ../inputs/grep*.dat  > ../outputs/t302 2>&1

echo ">>>>>>>>running test 303"
../source/grep.exe -G '?''\{1\}.:' ../inputs/grep*.dat  > ../outputs/t303 2>&1

echo ">>>>>>>>running test 304"
../source/grep.exe -G '\*\{1\}p.eg' ../inputs/grep*.dat  > ../outputs/t304 2>&1

echo ">>>>>>>>running test 305"
../source/grep.exe -G 'Include\|n''\{1\}.lud' ../inputs/grep*.dat  > ../outputs/t305 2>&1

echo ">>>>>>>>running test 306"
../source/grep.exe 'Include\|n\{1\}''.lud' ../inputs/grep*.dat  > ../outputs/t306 2>&1

echo ">>>>>>>>running test 307"
../source/grep.exe '\(Include\|n\{1\}\)''.lud' ../inputs/grep*.dat  > ../outputs/t307 2>&1

echo ">>>>>>>>running test 308"
../source/grep.exe -G 'Include\|n\{1\}.lude' ../inputs/grep*.dat  > ../outputs/t308 2>&1

echo ">>>>>>>>running test 309"
../source/grep.exe 'n''\{1\}.lude' ../inputs/grep*.dat  > ../outputs/t309 2>&1

echo ">>>>>>>>running test 310"
../source/grep.exe -G 'n\{1\}.lud' ../inputs/grep*.dat  > ../outputs/t310 2>&1

echo ">>>>>>>>running test 311"
../source/grep.exe 'In.lude\|?''%' ../inputs/grep*.dat  > ../outputs/t311 2>&1

echo ">>>>>>>>running test 312"
../source/grep.exe '\(In.lude\|?\)''%' ../inputs/grep*.dat  > ../outputs/t312 2>&1

echo ">>>>>>>>running test 313"
../source/grep.exe -Gc 'In.lude\|?' ../inputs/grep*.dat  > ../outputs/t313 2>&1

echo ">>>>>>>>running test 314"
../source/grep.exe '\*\*''p.' ../inputs/grep*.dat  > ../outputs/t314 2>&1

echo ">>>>>>>>running test 315"
../source/grep.exe -G '\*p.eg' ../inputs/grep*.dat  > ../outputs/t315 2>&1

echo ">>>>>>>>running test 316"
../source/grep.exe -G 'Include\|?''\?%' ../inputs/grep*.dat  > ../outputs/t316 2>&1

echo ">>>>>>>>running test 317"
../source/grep.exe -G 'include\|?\?''%' ../inputs/grep*.dat  > ../outputs/t317 2>&1

echo ">>>>>>>>running test 318"
../source/grep.exe -G '\(include\|?\?\)''%' ../inputs/grep*.dat  > ../outputs/t318 2>&1

echo ">>>>>>>>running test 319"
../source/grep.exe -Gc 'Include\|?\?' ../inputs/grep*.dat  > ../outputs/t319 2>&1

echo ">>>>>>>>running test 320"
../source/grep.exe -G '?''\? :' ../inputs/grep*.dat  > ../outputs/t320 2>&1

echo ">>>>>>>>running test 321"
../source/grep.exe -G '\*\?preg' ../inputs/grep*.dat  > ../outputs/t321 2>&1

echo ">>>>>>>>running test 322"
../source/grep.exe -G 'Include\|n''\?clud' ../inputs/grep*.dat  > ../outputs/t322 2>&1

echo ">>>>>>>>running test 323"
../source/grep.exe 'main\|in\?''clude' ../inputs/grep*.dat  > ../outputs/t323 2>&1

echo ">>>>>>>>running test 324"
../source/grep.exe '\(main\|in\?\)''clude' ../inputs/grep*.dat  > ../outputs/t324 2>&1

echo ">>>>>>>>running test 325"
../source/grep.exe -G 'main\|n\?clude' ../inputs/grep*.dat  > ../outputs/t325 2>&1

echo ">>>>>>>>running test 326"
../source/grep.exe -G 'n''\?clude' ../inputs/grep*.dat  > ../outputs/t326 2>&1

echo ">>>>>>>>running test 327"
../source/grep.exe -G 'n\?clud' ../inputs/grep*.dat  > ../outputs/t327 2>&1

echo ">>>>>>>>running test 328"
../source/grep.exe -G 'Include\|?''\+%' ../inputs/grep*.dat  > ../outputs/t328 2>&1

echo ">>>>>>>>running test 329"
../source/grep.exe -G 'include\|?\+''%' ../inputs/grep*.dat  > ../outputs/t329 2>&1

echo ">>>>>>>>running test 330"
../source/grep.exe -G '\(include\|?\+\)''%' ../inputs/grep*.dat  > ../outputs/t330 2>&1

echo ">>>>>>>>running test 331"
../source/grep.exe -Gc 'Include\|?\+' ../inputs/grep*.dat  > ../outputs/t331 2>&1

echo ">>>>>>>>running test 332"
../source/grep.exe -G '?''\+ 0' ../inputs/grep*.dat  > ../outputs/t332 2>&1

echo ">>>>>>>>running test 333"
../source/grep.exe -G '\*\+preg' ../inputs/grep*.dat  > ../outputs/t333 2>&1

echo ">>>>>>>>running test 334"
../source/grep.exe -G 'main\|n''\+clud' ../inputs/grep*.dat  > ../outputs/t334 2>&1

echo ">>>>>>>>running test 335"
../source/grep.exe -G 'Include\|n\+''clud' ../inputs/grep*.dat  > ../outputs/t335 2>&1

echo ">>>>>>>>running test 336"
../source/grep.exe -G '\(Include\|n\+\)''clud' ../inputs/grep*.dat  > ../outputs/t336 2>&1

echo ">>>>>>>>running test 337"
../source/grep.exe -G 'Include\|n\+clude' ../inputs/grep*.dat  > ../outputs/t337 2>&1

echo ">>>>>>>>running test 338"
../source/grep.exe -G 'n''\+clude' ../inputs/grep*.dat  > ../outputs/t338 2>&1

echo ">>>>>>>>running test 339"
../source/grep.exe -G 'n\+clud' ../inputs/grep*.dat  > ../outputs/t339 2>&1

echo ">>>>>>>>running test 340"
../source/grep.exe -G 'Include\|?''\{1\}%' ../inputs/grep*.dat  > ../outputs/t340 2>&1

echo ">>>>>>>>running test 341"
../source/grep.exe -G 'include\|?\{1\}''%' ../inputs/grep*.dat  > ../outputs/t341 2>&1

echo ">>>>>>>>running test 342"
../source/grep.exe -G '\(include\|?\{1\}\)''%' ../inputs/grep*.dat  > ../outputs/t342 2>&1

echo ">>>>>>>>running test 343"
../source/grep.exe -Gc 'Include\|?\{1\}' ../inputs/grep*.dat  > ../outputs/t343 2>&1

echo ">>>>>>>>running test 344"
../source/grep.exe -G '?''\{1\} 0' ../inputs/grep*.dat  > ../outputs/t344 2>&1

echo ">>>>>>>>running test 345"
../source/grep.exe '\*\{1\}preg' ../inputs/grep*.dat  > ../outputs/t345 2>&1

echo ">>>>>>>>running test 346"
../source/grep.exe 'Include\|n''\{1\}clud' ../inputs/grep*.dat  > ../outputs/t346 2>&1

echo ">>>>>>>>running test 347"
../source/grep.exe -G 'main\|n\{1\}''clud' ../inputs/grep*.dat  > ../outputs/t347 2>&1

echo ">>>>>>>>running test 348"
../source/grep.exe -G '\(main\|n\{1\}\)''clud' ../inputs/grep*.dat  > ../outputs/t348 2>&1

echo ">>>>>>>>running test 349"
../source/grep.exe -G 'Include\|n\{1\}clude' ../inputs/grep*.dat  > ../outputs/t349 2>&1

echo ">>>>>>>>running test 350"
../source/grep.exe -G 'n''\{1\}clude' ../inputs/grep*.dat  > ../outputs/t350 2>&1

echo ">>>>>>>>running test 351"
../source/grep.exe 'n\{1\}clud' ../inputs/grep*.dat  > ../outputs/t351 2>&1

echo ">>>>>>>>running test 352"
../source/grep.exe -G 'Include\|?''%' ../inputs/grep*.dat  > ../outputs/t352 2>&1

echo ">>>>>>>>running test 353"
../source/grep.exe -G '\(Include\|?\)''%' ../inputs/grep*.dat  > ../outputs/t353 2>&1

echo ">>>>>>>>running test 354"
../source/grep.exe -Gc 'Include\|?' ../inputs/grep*.dat  > ../outputs/t354 2>&1

echo ">>>>>>>>running test 355"
../source/grep.exe -G 'static'' int' ../inputs/grep*.dat  > ../outputs/t355 2>&1

echo ">>>>>>>>running test 356"
../source/grep.exe '\*preg' ../inputs/grep*.dat  > ../outputs/t356 2>&1

echo ">>>>>>>>running test 357"
../source/grep.exe -G "[]X]\|end"" -" ../inputs/grep*.dat  > ../outputs/t357 2>&1

echo ">>>>>>>>running test 358"
../source/grep.exe -G "\([]X]\|end\)"" -" ../inputs/grep*.dat  > ../outputs/t358 2>&1

echo ">>>>>>>>running test 359"
../source/grep.exe -G "[]X]\|end" ../inputs/grep*.dat  > ../outputs/t359 2>&1

echo ">>>>>>>>running test 360"
../source/grep.exe "[]X]"" -" ../inputs/grep*.dat  > ../outputs/t360 2>&1

echo ">>>>>>>>running test 361"
../source/grep.exe -G "[]X]" ../inputs/grep*.dat  > ../outputs/t361 2>&1

echo ">>>>>>>>running test 362"
../source/grep.exe -G "^if (\?g\|if (""\?out" ../inputs/grep*.dat  > ../outputs/t362 2>&1

echo ">>>>>>>>running test 363"
../source/grep.exe -G "^if (\?g\|^if (\?""out" ../inputs/grep*.dat  > ../outputs/t363 2>&1

echo ">>>>>>>>running test 364"
../source/grep.exe -G "\(^if (\?g\|^if (\?\)""out" ../inputs/grep*.dat  > ../outputs/t364 2>&1

echo ">>>>>>>>running test 365"
../source/grep.exe -G "^if (\?g\|^if out" ../inputs/grep*.dat  > ../outputs/t365 2>&1

echo ">>>>>>>>running test 366"
../source/grep.exe -G "^if (""\?gout" ../inputs/grep*.dat  > ../outputs/t366 2>&1

echo ">>>>>>>>running test 367"
../source/grep.exe "^if (\?gout" ../inputs/grep*.dat  > ../outputs/t367 2>&1

echo ">>>>>>>>running test 368"
../source/grep.exe -G "^if a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t368 2>&1

echo ">>>>>>>>running test 369"
../source/grep.exe -G "^if a\?g\|^if a\?""out" ../inputs/grep*.dat  > ../outputs/t369 2>&1

echo ">>>>>>>>running test 370"
../source/grep.exe -G "\(^if a\?g\|^if a\?\)""out" ../inputs/grep*.dat  > ../outputs/t370 2>&1

echo ">>>>>>>>running test 371"
../source/grep.exe -G "^if a\?g\|^if out" ../inputs/grep*.dat  > ../outputs/t371 2>&1

echo ">>>>>>>>running test 372"
../source/grep.exe -G "^if a""\?gout" ../inputs/grep*.dat  > ../outputs/t372 2>&1

echo ">>>>>>>>running test 373"
../source/grep.exe -G "^if a\?gout" ../inputs/grep*.dat  > ../outputs/t373 2>&1

echo ">>>>>>>>running test 374"
../source/grep.exe -G "^if (\+g\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t374 2>&1

echo ">>>>>>>>running test 375"
../source/grep.exe -G "^if (\+g\|^if (\+""out" ../inputs/grep*.dat  > ../outputs/t375 2>&1

echo ">>>>>>>>running test 376"
../source/grep.exe -G "\(^if (\+g\|^if (\+\)""out" ../inputs/grep*.dat  > ../outputs/t376 2>&1

echo ">>>>>>>>running test 377"
../source/grep.exe -G "^if (\+g\|^if out" ../inputs/grep*.dat  > ../outputs/t377 2>&1

echo ">>>>>>>>running test 378"
../source/grep.exe -G "^if (""\+gout" ../inputs/grep*.dat  > ../outputs/t378 2>&1

echo ">>>>>>>>running test 379"
../source/grep.exe -G "^if (\+gout" ../inputs/grep*.dat  > ../outputs/t379 2>&1

echo ">>>>>>>>running test 380"
../source/grep.exe -G "^if a\+g\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t380 2>&1

echo ">>>>>>>>running test 381"
../source/grep.exe -G "^if a\+g\|^if a\+""out" ../inputs/grep*.dat  > ../outputs/t381 2>&1

echo ">>>>>>>>running test 382"
../source/grep.exe -G "\(^if a\+g\|^if a\+\)""out" ../inputs/grep*.dat  > ../outputs/t382 2>&1

echo ">>>>>>>>running test 383"
../source/grep.exe "^if a\+g\|^if out" ../inputs/grep*.dat  > ../outputs/t383 2>&1

echo ">>>>>>>>running test 384"
../source/grep.exe -G "^if a""\+gout" ../inputs/grep*.dat  > ../outputs/t384 2>&1

echo ">>>>>>>>running test 385"
../source/grep.exe -G "^if a\+gout" ../inputs/grep*.dat  > ../outputs/t385 2>&1

echo ">>>>>>>>running test 386"
../source/grep.exe -G "^if (\{1\}g\|if (""\{1\}out" ../inputs/grep*.dat  > ../outputs/t386 2>&1

echo ">>>>>>>>running test 387"
../source/grep.exe -G "^if (\{1\}g\|^if (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t387 2>&1

echo ">>>>>>>>running test 388"
../source/grep.exe -G "\(^if (\{1\}g\|^if (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t388 2>&1

echo ">>>>>>>>running test 389"
../source/grep.exe -G "^if (\{1\}g\|^if out" ../inputs/grep*.dat  > ../outputs/t389 2>&1

echo ">>>>>>>>running test 390"
../source/grep.exe -G "^if (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t390 2>&1

echo ">>>>>>>>running test 391"
../source/grep.exe -G "^if (\{1\}gout" ../inputs/grep*.dat  > ../outputs/t391 2>&1

echo ">>>>>>>>running test 392"
../source/grep.exe -G "^if a\{1\}g\|if a""\{1\}out" ../inputs/grep*.dat  > ../outputs/t392 2>&1

echo ">>>>>>>>running test 393"
../source/grep.exe "^if a\{1\}g\|^if a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t393 2>&1

echo ">>>>>>>>running test 394"
../source/grep.exe "\(^if a\{1\}g\|^if a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t394 2>&1

echo ">>>>>>>>running test 395"
../source/grep.exe -G "^if a\{1\}g\|^if out" ../inputs/grep*.dat  > ../outputs/t395 2>&1

echo ">>>>>>>>running test 396"
../source/grep.exe "^if a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t396 2>&1

echo ">>>>>>>>running test 397"
../source/grep.exe "^if a\{1\}gout" ../inputs/grep*.dat  > ../outputs/t397 2>&1

echo ">>>>>>>>running test 398"
../source/grep.exe -G "\<if (\?g\|if (""\?out" ../inputs/grep*.dat  > ../outputs/t398 2>&1

echo ">>>>>>>>running test 399"
../source/grep.exe -G "\<if (\?g\|\<if (\?""out" ../inputs/grep*.dat  > ../outputs/t399 2>&1

echo ">>>>>>>>running test 400"
../source/grep.exe -G "\(\<if (\?g\|\<if (\?\)""out" ../inputs/grep*.dat  > ../outputs/t400 2>&1

echo ">>>>>>>>running test 401"
../source/grep.exe -G "\<if (\?g\|\<if out" ../inputs/grep*.dat  > ../outputs/t401 2>&1

echo ">>>>>>>>running test 402"
../source/grep.exe -G "\<if (""\?gout" ../inputs/grep*.dat  > ../outputs/t402 2>&1

echo ">>>>>>>>running test 403"
../source/grep.exe -G "\<if (\?gout" ../inputs/grep*.dat  > ../outputs/t403 2>&1

echo ">>>>>>>>running test 404"
../source/grep.exe "\<if a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t404 2>&1

echo ">>>>>>>>running test 405"
../source/grep.exe -G "\<if a\?g\|\<if a\?""out" ../inputs/grep*.dat  > ../outputs/t405 2>&1

echo ">>>>>>>>running test 406"
../source/grep.exe -G "\(\<if a\?g\|\<if a\?\)""out" ../inputs/grep*.dat  > ../outputs/t406 2>&1

echo ">>>>>>>>running test 407"
../source/grep.exe -G "\<if a\?g\|\<if out" ../inputs/grep*.dat  > ../outputs/t407 2>&1

echo ">>>>>>>>running test 408"
../source/grep.exe "\<if a""\?gout" ../inputs/grep*.dat  > ../outputs/t408 2>&1

echo ">>>>>>>>running test 409"
../source/grep.exe -G "\<if a\?gout" ../inputs/grep*.dat  > ../outputs/t409 2>&1

echo ">>>>>>>>running test 410"
../source/grep.exe -G "\<if (\+g\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t410 2>&1

echo ">>>>>>>>running test 411"
../source/grep.exe -G "\<if (\+g\|\<if (\+""out" ../inputs/grep*.dat  > ../outputs/t411 2>&1

echo ">>>>>>>>running test 412"
../source/grep.exe -G "\(\<if (\+g\|\<if (\+\)""out" ../inputs/grep*.dat  > ../outputs/t412 2>&1

echo ">>>>>>>>running test 413"
../source/grep.exe -G "\<if (\+g\|\<if out" ../inputs/grep*.dat  > ../outputs/t413 2>&1

echo ">>>>>>>>running test 414"
../source/grep.exe -G "\<if (""\+gout" ../inputs/grep*.dat  > ../outputs/t414 2>&1

echo ">>>>>>>>running test 415"
../source/grep.exe -G "\<if (\+gout" ../inputs/grep*.dat  > ../outputs/t415 2>&1

echo ">>>>>>>>running test 416"
../source/grep.exe -G "\<if a\+g\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t416 2>&1

echo ">>>>>>>>running test 417"
../source/grep.exe -G "\<if a\+g\|\<if a\+""out" ../inputs/grep*.dat  > ../outputs/t417 2>&1

echo ">>>>>>>>running test 418"
../source/grep.exe -G "\(\<if a\+g\|\<if a\+\)""out" ../inputs/grep*.dat  > ../outputs/t418 2>&1

echo ">>>>>>>>running test 419"
../source/grep.exe -G "\<if a\+g\|\<if out" ../inputs/grep*.dat  > ../outputs/t419 2>&1

echo ">>>>>>>>running test 420"
../source/grep.exe "\<if a""\+gout" ../inputs/grep*.dat  > ../outputs/t420 2>&1

echo ">>>>>>>>running test 421"
../source/grep.exe -G "\<if a\+gout" ../inputs/grep*.dat  > ../outputs/t421 2>&1

echo ">>>>>>>>running test 422"
../source/grep.exe -G "\<if (\{1\}g\|if (""\{1\}out" ../inputs/grep*.dat  > ../outputs/t422 2>&1

echo ">>>>>>>>running test 423"
../source/grep.exe -G "\<if (\{1\}g\|\<if (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t423 2>&1

echo ">>>>>>>>running test 424"
../source/grep.exe -G "\(\<if (\{1\}g\|\<if (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t424 2>&1

echo ">>>>>>>>running test 425"
../source/grep.exe -G "\<if (\{1\}g\|\<if out" ../inputs/grep*.dat  > ../outputs/t425 2>&1

echo ">>>>>>>>running test 426"
../source/grep.exe "\<if (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t426 2>&1

echo ">>>>>>>>running test 427"
../source/grep.exe -G "\<if (\{1\}gout" ../inputs/grep*.dat  > ../outputs/t427 2>&1

echo ">>>>>>>>running test 428"
../source/grep.exe -G "\<if a\{1\}g\|if a""\{1\}out" ../inputs/grep*.dat  > ../outputs/t428 2>&1

echo ">>>>>>>>running test 429"
../source/grep.exe -G "\<if a\{1\}g\|\<if a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t429 2>&1

echo ">>>>>>>>running test 430"
../source/grep.exe -G "\(\<if a\{1\}g\|\<if a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t430 2>&1

echo ">>>>>>>>running test 431"
../source/grep.exe -G "\<if a\{1\}g\|\<if out" ../inputs/grep*.dat  > ../outputs/t431 2>&1

echo ">>>>>>>>running test 432"
../source/grep.exe -G "\<if a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t432 2>&1

echo ">>>>>>>>running test 433"
../source/grep.exe -G "\<if a\{1\}gout" ../inputs/grep*.dat  > ../outputs/t433 2>&1

echo ">>>>>>>>running test 434"
../source/grep.exe "\bif (\?g\|if (""\?out\b" ../inputs/grep*.dat  > ../outputs/t434 2>&1

echo ">>>>>>>>running test 435"
../source/grep.exe -G "\bif (\?g\|\bif (\?""out" ../inputs/grep*.dat  > ../outputs/t435 2>&1

echo ">>>>>>>>running test 436"
../source/grep.exe -G "\(\bif (\?g\|\bif (\?\)""out" ../inputs/grep*.dat  > ../outputs/t436 2>&1

echo ">>>>>>>>running test 437"
../source/grep.exe "\bif (\?g\b\|\bif out" ../inputs/grep*.dat  > ../outputs/t437 2>&1

echo ">>>>>>>>running test 438"
../source/grep.exe -G "\bif (""\?gout" ../inputs/grep*.dat  > ../outputs/t438 2>&1

echo ">>>>>>>>running test 439"
../source/grep.exe -G "\bif (\?gout\b" ../inputs/grep*.dat  > ../outputs/t439 2>&1

echo ">>>>>>>>running test 440"
../source/grep.exe -G "\bif a\?g\|if a""\?out" ../inputs/grep*.dat  > ../outputs/t440 2>&1

echo ">>>>>>>>running test 441"
../source/grep.exe "\bif a\?g\|\bif a\?""out" ../inputs/grep*.dat  > ../outputs/t441 2>&1

echo ">>>>>>>>running test 442"
../source/grep.exe "\(\bif a\?g\|\bif a\?\)""out" ../inputs/grep*.dat  > ../outputs/t442 2>&1

echo ">>>>>>>>running test 443"
../source/grep.exe -G "\bif a\?g\|\bif out\b" ../inputs/grep*.dat  > ../outputs/t443 2>&1

echo ">>>>>>>>running test 444"
../source/grep.exe -G "\bif a""\?gout\b" ../inputs/grep*.dat  > ../outputs/t444 2>&1

echo ">>>>>>>>running test 445"
../source/grep.exe -G "\bif a\?gout" ../inputs/grep*.dat  > ../outputs/t445 2>&1

echo ">>>>>>>>running test 446"
../source/grep.exe -G "\bif (\+g\b\|if (""\+out" ../inputs/grep*.dat  > ../outputs/t446 2>&1

echo ">>>>>>>>running test 447"
../source/grep.exe "\bif (\+g\|\bif (\+""out" ../inputs/grep*.dat  > ../outputs/t447 2>&1

echo ">>>>>>>>running test 448"
../source/grep.exe "\(\bif (\+g\|\bif (\+\)""out" ../inputs/grep*.dat  > ../outputs/t448 2>&1

echo ">>>>>>>>running test 449"
../source/grep.exe -G "\bif (\+g\|\bif out" ../inputs/grep*.dat  > ../outputs/t449 2>&1

echo ">>>>>>>>running test 450"
../source/grep.exe -G "\bif (""\+gout\b" ../inputs/grep*.dat  > ../outputs/t450 2>&1

echo ">>>>>>>>running test 451"
../source/grep.exe -G "\bif (\+gout" ../inputs/grep*.dat  > ../outputs/t451 2>&1

echo ">>>>>>>>running test 452"
../source/grep.exe -G "\bif a\+g\b\|if a""\+out" ../inputs/grep*.dat  > ../outputs/t452 2>&1

echo ">>>>>>>>running test 453"
../source/grep.exe -G "if a\+g\b\|\bif a\+""out" ../inputs/grep*.dat  > ../outputs/t453 2>&1

echo ">>>>>>>>running test 454"
../source/grep.exe -G "\(if a\+g\b\|\bif a\+\)""out" ../inputs/grep*.dat  > ../outputs/t454 2>&1

echo ">>>>>>>>running test 455"
../source/grep.exe -G "\bif a\+g\|\bif out" ../inputs/grep*.dat  > ../outputs/t455 2>&1

echo ">>>>>>>>running test 456"
../source/grep.exe -G "if a""\+gout\b" ../inputs/grep*.dat  > ../outputs/t456 2>&1

echo ">>>>>>>>running test 457"
../source/grep.exe "if a\+gout\b" ../inputs/grep*.dat  > ../outputs/t457 2>&1

echo ">>>>>>>>running test 458"
../source/grep.exe -G "\bif (\{1\}g\|if (""\{1\}out\b" ../inputs/grep*.dat  > ../outputs/t458 2>&1

echo ">>>>>>>>running test 459"
../source/grep.exe -G "\bif (\{1\}g\|\bif (\{1\}""out" ../inputs/grep*.dat  > ../outputs/t459 2>&1

echo ">>>>>>>>running test 460"
../source/grep.exe -G "\(\bif (\{1\}g\|\bif (\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t460 2>&1

echo ">>>>>>>>running test 461"
../source/grep.exe -G "\bif (\{1\}g\|\bif out" ../inputs/grep*.dat  > ../outputs/t461 2>&1

echo ">>>>>>>>running test 462"
../source/grep.exe "\bif (""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t462 2>&1

echo ">>>>>>>>running test 463"
../source/grep.exe "\bif (\{1\}gout\b" ../inputs/grep*.dat  > ../outputs/t463 2>&1

echo ">>>>>>>>running test 464"
../source/grep.exe -G "\bif a\{1\}g\|if a""\{1\}out\b" ../inputs/grep*.dat  > ../outputs/t464 2>&1

echo ">>>>>>>>running test 465"
../source/grep.exe -G "\bif a\{1\}g\|\bif a\{1\}""out" ../inputs/grep*.dat  > ../outputs/t465 2>&1

echo ">>>>>>>>running test 466"
../source/grep.exe -G "\(\bif a\{1\}g\|\bif a\{1\}\)""out" ../inputs/grep*.dat  > ../outputs/t466 2>&1

echo ">>>>>>>>running test 467"
../source/grep.exe -G "if a\{1\}g\b\|\bif out" ../inputs/grep*.dat  > ../outputs/t467 2>&1

echo ">>>>>>>>running test 468"
../source/grep.exe -G "\bif a""\{1\}gout" ../inputs/grep*.dat  > ../outputs/t468 2>&1

echo ">>>>>>>>running test 469"
../source/grep.exe -G "if a\{1\}gout\b" ../inputs/grep*.dat  > ../outputs/t469 2>&1

echo ">>>>>>>>running test 470"
../source/grep.exe -Gc static ../inputs/grep*.dat  > ../outputs/t470 2>&1

echo ">>>>>>>>running test 471"
../source/grep.exe -n I ../inputs/grep1.dat  > ../outputs/t471 2>&1

echo ">>>>>>>>running test 472"
../source/grep.exe -n "/* The following list maps the names of the Posix named character classes static int laststart;True if we're separated from beginning or (, |" ../inputs/grep1.dat  > ../outputs/t472 2>&1

echo ">>>>>>>>running test 473"
../source/grep.exe -c "/n" ../inputs/grep1.dat  > ../outputs/t473 2>&1

echo ">>>>>>>>running test 474"
../source/grep.exe -b 'static int' ../inputs/grep1.dat  > ../outputs/t474 2>&1

echo ">>>>>>>>running test 475"
../source/grep.exe 'if (! lexleft)' ../inputs/grep1.dat  > ../outputs/t475 2>&1

echo ">>>>>>>>running test 476"
../source/grep.exe -G ' ":xdigit:]", is_xdigit' ../inputs/grep1.dat  > ../outputs/t476 2>&1

echo ">>>>>>>>running test 477"
../source/grep.exe "case ')':" ../inputs/grep1.dat  > ../outputs/t477 2>&1

echo ">>>>>>>>running test 478"
../source/grep.exe "< PEND'" ../inputs/grep1.dat  > ../outputs/t478 2>&1

echo ">>>>>>>>running test 479"
../source/grep.exe -G ' ":xdigit:]' ../inputs/grep1.dat  > ../outputs/t479 2>&1

echo ">>>>>>>>running test 480"
../source/grep.exe ../inputs/grep0.dat ../inputs/grep1.dat  > ../outputs/t480 2>&1

echo ">>>>>>>>running test 481"
../source/grep.exe -w in ../inputs/grep1.dat  > ../outputs/t481 2>&1

echo ">>>>>>>>running test 482"
../source/grep.exe -x " return" ../inputs/grep1.dat  > ../outputs/t482 2>&1

echo ">>>>>>>>running test 483"
../source/grep.exe -V  > ../outputs/t483 2>&1

echo ">>>>>>>>running test 484"
../source/grep.exe -B 2 return ../inputs/grep1.dat  > ../outputs/t484 2>&1

echo ">>>>>>>>running test 485"
../source/grep.exe -A 2 return ../inputs/grep1.dat  > ../outputs/t485 2>&1

echo ">>>>>>>>running test 486"
../source/grep.exe -B 2 -A 3 return ../inputs/grep1.dat  > ../outputs/t486 2>&1

echo ">>>>>>>>running test 487"
../source/grep.exe -C return ../inputs/grep1.dat  > ../outputs/t487 2>&1

echo ">>>>>>>>running test 488"
../source/grep.exe -3 return ../inputs/grep1.dat  > ../outputs/t488 2>&1

echo ">>>>>>>>running test 489"
../source/grep.exe -q include ../inputs/grep1.dat  > ../outputs/t489 2>&1

echo ">>>>>>>>running test 490"
../source/grep.exe -c include < ../inputs/grep1.dat > ../outputs/t490 2>&1

echo ">>>>>>>>running test 491"
../source/grep.exe -c include - < ../inputs/grep1.dat > ../outputs/t491 2>&1

echo ">>>>>>>>running test 492"
../source/grep.exe -s 'return' ../inputs/grepNon.dat  > ../outputs/t492 2>&1

echo ">>>>>>>>running test 493"
../source/grep.exe -c TGGG ../inputs/grep1.dat  > ../outputs/t493 2>&1

echo ">>>>>>>>running test 494"
../source/grep.exe 'When group 3 ends' ../inputs/grep1.dat  > ../outputs/t494 2>&1

echo ">>>>>>>>running test 495"
../source/grep.exe size ../inputs/grep1.dat  > ../outputs/t495 2>&1

echo ">>>>>>>>running test 496"
../source/grep.exe -L "" ../inputs/grepNon.dat  > ../outputs/t496 2>&1

echo ">>>>>>>>running test 497"
../source/grep.exe -L "" ../inputs/grep1.dat  > ../outputs/t497 2>&1

echo ">>>>>>>>running test 498"
../source/grep.exe -L "" ../inputs/grep*.dat  > ../outputs/t498 2>&1

echo ">>>>>>>>running test 499"
../source/grep.exe -c "" ../inputs/grepNon.dat  > ../outputs/t499 2>&1

echo ">>>>>>>>running test 500"
../source/grep.exe -c "" ../inputs/grep1.dat  > ../outputs/t500 2>&1

echo ">>>>>>>>running test 501"
../source/grep.exe -c "" ../inputs/grep*.dat  > ../outputs/t501 2>&1

echo ">>>>>>>>running test 502"
../source/grep.exe -nbh '' ../inputs/grepNon.dat  > ../outputs/t502 2>&1

echo ">>>>>>>>running test 503"
../source/grep.exe -nbh '' ../inputs/grep1.dat  > ../outputs/t503 2>&1

echo ">>>>>>>>running test 504"
../source/grep.exe -nbh '' ../inputs/grep*.dat  > ../outputs/t504 2>&1

echo ">>>>>>>>running test 505"
../source/grep.exe -ile --beg ../inputs/grep1.dat  > ../outputs/t505 2>&1

echo ">>>>>>>>running test 506"
../source/grep.exe -ile --beg ../inputs/grep*.dat  > ../outputs/t506 2>&1

echo ">>>>>>>>running test 507"
../source/grep.exe -ivL "include" ../inputs/grep1.dat  > ../outputs/t507 2>&1

echo ">>>>>>>>running test 508"
../source/grep.exe -ivL "struct trie" ../inputs/grep*.dat  > ../outputs/t508 2>&1

echo ">>>>>>>>running test 509"
../source/grep.exe -ivc "include" ../inputs/grep1.dat  > ../outputs/t509 2>&1

echo ">>>>>>>>running test 510"
../source/grep.exe -ivc "include" ../inputs/grep*.dat  > ../outputs/t510 2>&1

echo ">>>>>>>>running test 511"
../source/grep.exe -vL "include" ../inputs/grep1.dat  > ../outputs/t511 2>&1

echo ">>>>>>>>running test 512"
../source/grep.exe -vL "include" ../inputs/grep*.dat  > ../outputs/t512 2>&1

echo ">>>>>>>>running test 513"
../source/grep.exe -vc "include" ../inputs/grep1.dat  > ../outputs/t513 2>&1

echo ">>>>>>>>running test 514"
../source/grep.exe -vc "include" ../inputs/grep*.dat  > ../outputs/t514 2>&1

echo ">>>>>>>>running test 515"
../source/grep.exe -iL "include" ../inputs/grep1.dat  > ../outputs/t515 2>&1

echo ">>>>>>>>running test 516"
../source/grep.exe -iL "include" ../inputs/grep*.dat  > ../outputs/t516 2>&1

echo ">>>>>>>>running test 517"
../source/grep.exe -ic "include" ../inputs/grep1.dat  > ../outputs/t517 2>&1

echo ">>>>>>>>running test 518"
../source/grep.exe -ic "include" ../inputs/grep*.dat  > ../outputs/t518 2>&1

echo ">>>>>>>>running test 519"
../source/grep.exe -L "include" ../inputs/grep1.dat  > ../outputs/t519 2>&1

echo ">>>>>>>>running test 520"
../source/grep.exe -L "include" ../inputs/grep*.dat  > ../outputs/t520 2>&1

echo ">>>>>>>>running test 521"
../source/grep.exe -c "include" ../inputs/grep1.dat  > ../outputs/t521 2>&1

echo ">>>>>>>>running test 522"
../source/grep.exe -c "include" ../inputs/grep*.dat  > ../outputs/t522 2>&1

echo ">>>>>>>>running test 523"
../source/grep.exe -vinbh 'include' ../inputs/grep1.dat  > ../outputs/t523 2>&1

echo ">>>>>>>>running test 524"
../source/grep.exe -vinbh 'include' ../inputs/grep*.dat  > ../outputs/t524 2>&1

echo ">>>>>>>>running test 525"
../source/grep.exe -vinb 'include' ../inputs/grep1.dat  > ../outputs/t525 2>&1

echo ">>>>>>>>running test 526"
../source/grep.exe -vinb 'include' ../inputs/grep*.dat  > ../outputs/t526 2>&1

echo ">>>>>>>>running test 527"
../source/grep.exe -vinh 'include' ../inputs/grep1.dat  > ../outputs/t527 2>&1

echo ">>>>>>>>running test 528"
../source/grep.exe -vinh 'include' ../inputs/grep*.dat  > ../outputs/t528 2>&1

echo ">>>>>>>>running test 529"
../source/grep.exe -vin 'include' ../inputs/grep1.dat  > ../outputs/t529 2>&1

echo ">>>>>>>>running test 530"
../source/grep.exe -vin 'include' ../inputs/grep*.dat  > ../outputs/t530 2>&1

echo ">>>>>>>>running test 531"
../source/grep.exe -vbhn 'include' ../inputs/grep1.dat  > ../outputs/t531 2>&1

echo ">>>>>>>>running test 532"
../source/grep.exe -vbhn 'include' ../inputs/grep*.dat  > ../outputs/t532 2>&1

echo ">>>>>>>>running test 533"
../source/grep.exe -vbn 'include' ../inputs/grep1.dat  > ../outputs/t533 2>&1

echo ">>>>>>>>running test 534"
../source/grep.exe -vbn 'include' ../inputs/grep*.dat  > ../outputs/t534 2>&1

echo ">>>>>>>>running test 535"
../source/grep.exe -vnh 'include' ../inputs/grep1.dat  > ../outputs/t535 2>&1

echo ">>>>>>>>running test 536"
../source/grep.exe -vnh 'include' ../inputs/grep*.dat  > ../outputs/t536 2>&1

echo ">>>>>>>>running test 537"
../source/grep.exe -vn 'include' ../inputs/grep1.dat  > ../outputs/t537 2>&1

echo ">>>>>>>>running test 538"
../source/grep.exe -vn 'include' ../inputs/grep*.dat  > ../outputs/t538 2>&1

echo ">>>>>>>>running test 539"
../source/grep.exe -inbh 'include' ../inputs/grep1.dat  > ../outputs/t539 2>&1

echo ">>>>>>>>running test 540"
../source/grep.exe -inbh 'include' ../inputs/grep*.dat  > ../outputs/t540 2>&1

echo ">>>>>>>>running test 541"
../source/grep.exe -inb 'include' ../inputs/grep1.dat  > ../outputs/t541 2>&1

echo ">>>>>>>>running test 542"
../source/grep.exe -inb 'include' ../inputs/grep*.dat  > ../outputs/t542 2>&1

echo ">>>>>>>>running test 543"
../source/grep.exe -inh 'include' ../inputs/grep1.dat  > ../outputs/t543 2>&1

echo ">>>>>>>>running test 544"
../source/grep.exe -inh 'include' ../inputs/grep*.dat  > ../outputs/t544 2>&1

echo ">>>>>>>>running test 545"
../source/grep.exe -in 'include' ../inputs/grep1.dat  > ../outputs/t545 2>&1

echo ">>>>>>>>running test 546"
../source/grep.exe -in 'include' ../inputs/grep*.dat  > ../outputs/t546 2>&1

echo ">>>>>>>>running test 547"
../source/grep.exe -nbh 'include' ../inputs/grep1.dat  > ../outputs/t547 2>&1

echo ">>>>>>>>running test 548"
../source/grep.exe -nbh 'include' ../inputs/grep*.dat  > ../outputs/t548 2>&1

echo ">>>>>>>>running test 549"
../source/grep.exe -nb 'include' ../inputs/grep1.dat  > ../outputs/t549 2>&1

echo ">>>>>>>>running test 550"
../source/grep.exe -nb 'include' ../inputs/grep*.dat  > ../outputs/t550 2>&1

echo ">>>>>>>>running test 551"
../source/grep.exe -nh 'include' ../inputs/grep1.dat  > ../outputs/t551 2>&1

echo ">>>>>>>>running test 552"
../source/grep.exe -nh 'include' ../inputs/grep*.dat  > ../outputs/t552 2>&1

echo ">>>>>>>>running test 553"
../source/grep.exe -n 'include' ../inputs/grep1.dat  > ../outputs/t553 2>&1

echo ">>>>>>>>running test 554"
../source/grep.exe -n 'include' ../inputs/grep*.dat  > ../outputs/t554 2>&1

echo ">>>>>>>>running test 555"
../source/grep.exe -vil 'include' ../inputs/grep1.dat  > ../outputs/t555 2>&1

echo ">>>>>>>>running test 556"
../source/grep.exe -vil 'include' ../inputs/grep*.dat  > ../outputs/t556 2>&1

echo ">>>>>>>>running test 557"
../source/grep.exe -vibh TGGGG ../inputs/grepBinary  > ../outputs/t557 2>&1

echo ">>>>>>>>running test 558"
../source/grep.exe -vibh include ../inputs/grep1.dat  > ../outputs/t558 2>&1

echo ">>>>>>>>running test 559"
../source/grep.exe -vibh include ../inputs/grep*.dat  > ../outputs/t559 2>&1

echo ">>>>>>>>running test 560"
../source/grep.exe -vib TGGGG ../inputs/grepBinary  > ../outputs/t560 2>&1

echo ">>>>>>>>running test 561"
../source/grep.exe -vib include ../inputs/grep1.dat  > ../outputs/t561 2>&1

echo ">>>>>>>>running test 562"
../source/grep.exe -vib include ../inputs/grep*.dat  > ../outputs/t562 2>&1

echo ">>>>>>>>running test 563"
../source/grep.exe -vih TGGGG ../inputs/grepBinary  > ../outputs/t563 2>&1

echo ">>>>>>>>running test 564"
../source/grep.exe -vih include ../inputs/grep1.dat  > ../outputs/t564 2>&1

echo ">>>>>>>>running test 565"
../source/grep.exe -vih include ../inputs/grep*.dat  > ../outputs/t565 2>&1

echo ">>>>>>>>running test 566"
../source/grep.exe -vi TGGGG ../inputs/grepBinary  > ../outputs/t566 2>&1

echo ">>>>>>>>running test 567"
../source/grep.exe -vi include ../inputs/grep1.dat  > ../outputs/t567 2>&1

echo ">>>>>>>>running test 568"
../source/grep.exe -vi include ../inputs/grep*.dat  > ../outputs/t568 2>&1

echo ">>>>>>>>running test 569"
../source/grep.exe -vl include ../inputs/grep1.dat  > ../outputs/t569 2>&1

echo ">>>>>>>>running test 570"
../source/grep.exe -vl include ../inputs/grep*.dat  > ../outputs/t570 2>&1

echo ">>>>>>>>running test 571"
../source/grep.exe -vbh Tgggg ../inputs/grepBinary  > ../outputs/t571 2>&1

echo ">>>>>>>>running test 572"
../source/grep.exe -vbh include ../inputs/grep1.dat  > ../outputs/t572 2>&1

echo ">>>>>>>>running test 573"
../source/grep.exe -vbh include ../inputs/grep*.dat  > ../outputs/t573 2>&1

echo ">>>>>>>>running test 574"
../source/grep.exe -vb Tgggg ../inputs/grepBinary  > ../outputs/t574 2>&1

echo ">>>>>>>>running test 575"
../source/grep.exe -vb include ../inputs/grep1.dat  > ../outputs/t575 2>&1

echo ">>>>>>>>running test 576"
../source/grep.exe -vb include ../inputs/grep*.dat  > ../outputs/t576 2>&1

echo ">>>>>>>>running test 577"
../source/grep.exe -vh Tgggg ../inputs/grepBinary  > ../outputs/t577 2>&1

echo ">>>>>>>>running test 578"
../source/grep.exe -vh include ../inputs/grep1.dat  > ../outputs/t578 2>&1

echo ">>>>>>>>running test 579"
../source/grep.exe -vh include ../inputs/grep*.dat  > ../outputs/t579 2>&1

echo ">>>>>>>>running test 580"
../source/grep.exe -v Tgggg ../inputs/grepBinary  > ../outputs/t580 2>&1

echo ">>>>>>>>running test 581"
../source/grep.exe -v include ../inputs/grep1.dat  > ../outputs/t581 2>&1

echo ">>>>>>>>running test 582"
../source/grep.exe -v include ../inputs/grep*.dat  > ../outputs/t582 2>&1

echo ">>>>>>>>running test 583"
../source/grep.exe -il include ../inputs/grep1.dat  > ../outputs/t583 2>&1

echo ">>>>>>>>running test 584"
../source/grep.exe -il include ../inputs/grep*.dat  > ../outputs/t584 2>&1

echo ">>>>>>>>running test 585"
../source/grep.exe -ibh Tgggg ../inputs/grepBinary  > ../outputs/t585 2>&1

echo ">>>>>>>>running test 586"
../source/grep.exe -ibh include ../inputs/grep1.dat  > ../outputs/t586 2>&1

echo ">>>>>>>>running test 587"
../source/grep.exe -ibh include ../inputs/grep*.dat  > ../outputs/t587 2>&1

echo ">>>>>>>>running test 588"
../source/grep.exe -ib Tgggg ../inputs/grepBinary  > ../outputs/t588 2>&1

echo ">>>>>>>>running test 589"
../source/grep.exe -ib include ../inputs/grep1.dat  > ../outputs/t589 2>&1

echo ">>>>>>>>running test 590"
../source/grep.exe -ib include ../inputs/grep*.dat  > ../outputs/t590 2>&1

echo ">>>>>>>>running test 591"
../source/grep.exe -ih Tgggg ../inputs/grepBinary  > ../outputs/t591 2>&1

echo ">>>>>>>>running test 592"
../source/grep.exe -ih include ../inputs/grep1.dat  > ../outputs/t592 2>&1

echo ">>>>>>>>running test 593"
../source/grep.exe -ih include ../inputs/grep*.dat  > ../outputs/t593 2>&1

echo ">>>>>>>>running test 594"
../source/grep.exe -i Tgggg ../inputs/grepBinary  > ../outputs/t594 2>&1

echo ">>>>>>>>running test 595"
../source/grep.exe -i include ../inputs/grep1.dat  > ../outputs/t595 2>&1

echo ">>>>>>>>running test 596"
../source/grep.exe -i include ../inputs/grep*.dat  > ../outputs/t596 2>&1

echo ">>>>>>>>running test 597"
../source/grep.exe -l include ../inputs/grep1.dat  > ../outputs/t597 2>&1

echo ">>>>>>>>running test 598"
../source/grep.exe -l include ../inputs/grep*.dat  > ../outputs/t598 2>&1

echo ">>>>>>>>running test 599"
../source/grep.exe -bh Tgggg ../inputs/grepBinary  > ../outputs/t599 2>&1

echo ">>>>>>>>running test 600"
../source/grep.exe -bh include ../inputs/grep1.dat  > ../outputs/t600 2>&1

echo ">>>>>>>>running test 601"
../source/grep.exe -bh include ../inputs/grep*.dat  > ../outputs/t601 2>&1

echo ">>>>>>>>running test 602"
../source/grep.exe -b Tgggg ../inputs/grepBinary  > ../outputs/t602 2>&1

echo ">>>>>>>>running test 603"
../source/grep.exe -b include ../inputs/grep1.dat  > ../outputs/t603 2>&1

echo ">>>>>>>>running test 604"
../source/grep.exe -b include ../inputs/grep*.dat  > ../outputs/t604 2>&1

echo ">>>>>>>>running test 605"
../source/grep.exe -h Tgggg ../inputs/grepBinary  > ../outputs/t605 2>&1

echo ">>>>>>>>running test 606"
../source/grep.exe -h include ../inputs/grep1.dat  > ../outputs/t606 2>&1

echo ">>>>>>>>running test 607"
../source/grep.exe -h include ../inputs/grep*.dat  > ../outputs/t607 2>&1

echo ">>>>>>>>running test 608"
../source/grep.exe Tgggg ../inputs/grepBinary  > ../outputs/t608 2>&1

echo ">>>>>>>>running test 609"
../source/grep.exe include ../inputs/grep1.dat  > ../outputs/t609 2>&1

echo ">>>>>>>>running test 610"
../source/grep.exe include ../inputs/grep*.dat  > ../outputs/t610 2>&1

echo ">>>>>>>>running test 611"
../source/grep.exe -0 12345 ../inputs/grep1.dat  > ../outputs/t611 2>&1

echo ">>>>>>>>running test 612"
../source/grep.exe -1 12345 ../inputs/grep1.dat  > ../outputs/t612 2>&1

echo ">>>>>>>>running test 613"
../source/grep.exe -2 12345 ../inputs/grep1.dat  > ../outputs/t613 2>&1

echo ">>>>>>>>running test 614"
../source/grep.exe -3 12345 ../inputs/grep1.dat  > ../outputs/t614 2>&1

echo ">>>>>>>>running test 615"
../source/grep.exe -4 12345 ../inputs/grep1.dat  > ../outputs/t615 2>&1

echo ">>>>>>>>running test 616"
../source/grep.exe -5 12345 ../inputs/grep1.dat  > ../outputs/t616 2>&1

echo ">>>>>>>>running test 617"
../source/grep.exe -6 12345 ../inputs/grep1.dat  > ../outputs/t617 2>&1

echo ">>>>>>>>running test 618"
../source/grep.exe -7 12345 ../inputs/grep1.dat  > ../outputs/t618 2>&1

echo ">>>>>>>>running test 619"
../source/grep.exe -8 12345 ../inputs/grep1.dat  > ../outputs/t619 2>&1

echo ">>>>>>>>running test 620"
../source/grep.exe -9 12345 ../inputs/grep1.dat  > ../outputs/t620 2>&1

echo ">>>>>>>>running test 621"
../source/grep.exe -f 12345 ../inputs/grep1.dat  > ../outputs/t621 2>&1

echo ">>>>>>>>running test 622"
../source/grep.exe -i 12345 ../inputs/grep1.dat  > ../outputs/t622 2>&1

echo ">>>>>>>>running test 623"
../source/grep.exe -Y 12345 ../inputs/grep1.dat  > ../outputs/t623 2>&1

echo ">>>>>>>>running test 624"
../source/grep.exe -A -12345 ../inputs/grep1.dat  > ../outputs/t624 2>&1

echo ">>>>>>>>running test 625"
../source/grep.exe -B -12345 ../inputs/grep1.dat  > ../outputs/t625 2>&1

echo ">>>>>>>>running test 626"
../source/grep.exe -F -E 12345 ../inputs/grep1.dat  > ../outputs/t626 2>&1

echo ">>>>>>>>running test 627"
../source/grep.exe -E -F 12345 ../inputs/grep1.dat  > ../outputs/t627 2>&1

echo ">>>>>>>>running test 628"
../source/grep.exe -E -G 12345 ../inputs/grep1.dat  > ../outputs/t628 2>&1

echo ">>>>>>>>running test 629"
../source/grep.exe -G -X 12345 ../inputs/grep1.dat  > ../outputs/t629 2>&1

echo ">>>>>>>>running test 630"
../source/grep.exe -f nosuchfile ../inputs/grep1.dat  > ../outputs/t630 2>&1

echo ">>>>>>>>running test 631"
../source/grep.exe -f ../inputs/grep1.dat ../inputs/grep1.dat  > ../outputs/t631 2>&1

echo ">>>>>>>>running test 632"
../source/grep.exe -c 12345a < ../inputs/grep1.dat > ../outputs/t632 2>&1

echo ">>>>>>>>running test 633"
../source/grep.exe 12345a < ../inputs/grep1.dat > ../outputs/t633 2>&1

echo ">>>>>>>>running test 634"
../source/grep.exe -c include < ../inputs/grep1.dat > ../outputs/t634 2>&1

echo ">>>>>>>>running test 635"
../source/grep.exe include < ../inputs/grep1.dat > ../outputs/t635 2>&1

echo ">>>>>>>>running test 636"
../source/grep.exe include ../inputs/grep1.dat  > ../outputs/t636 2>&1

echo ">>>>>>>>running test 637"
../source/grep.exe -l include < ../inputs/../inputs/grep1.dat > ../outputs/t637 2>&1

echo ">>>>>>>>running test 638"
../source/grep.exe -L 12345a < ../inputs/../inputs/grep1.dat > ../outputs/t638 2>&1

echo ">>>>>>>>running test 639"
../source/grep.exe 12345a < ../inputs/../inputs/grep1.dat > ../outputs/t639 2>&1

echo ">>>>>>>>running test 640"
../source/grep.exe "--" 12345 ../inputs/grep1.dat  > ../outputs/t640 2>&1

echo ">>>>>>>>running test 641"
../source/grep.exe - -- 12345 ../inputs/grep1.dat  > ../outputs/t641 2>&1

echo ">>>>>>>>running test 642"
../source/grep.exe "[z-a]" ../inputs/grep1.dat  > ../outputs/t642 2>&1

echo ">>>>>>>>running test 643"
../source/grep.exe "[5-1]" ../inputs/grep1.dat  > ../outputs/t643 2>&1

echo ">>>>>>>>running test 644"
../source/grep.exe "[F-A]" ../inputs/grep1.dat  > ../outputs/t644 2>&1

echo ">>>>>>>>running test 645"
../source/grep.exe -ff  > ../outputs/t645 2>&1

echo ">>>>>>>>running test 646"
../source/grep.exe -f  > ../outputs/t646 2>&1

echo ">>>>>>>>running test 647"
../source/grep.exe 'a$a' ../inputs/grep1.dat  > ../outputs/t647 2>&1

echo ">>>>>>>>running test 648"
../source/grep.exe 'if$' ../inputs/grep1.dat  > ../outputs/t648 2>&1

echo ">>>>>>>>running test 649"
../source/grep.exe 'switch$|else' ../inputs/grep1.dat  > ../outputs/t649 2>&1

echo ">>>>>>>>running test 650"
../source/grep.exe "1\+\+" ../inputs/grep1.dat  > ../outputs/t650 2>&1

echo ">>>>>>>>running test 651"
../source/grep.exe "1\?\+" ../inputs/grep1.dat  > ../outputs/t651 2>&1

echo ">>>>>>>>running test 652"
../source/grep.exe "1\+\?" ../inputs/grep1.dat  > ../outputs/t652 2>&1

echo ">>>>>>>>running test 653"
../source/grep.exe "[" ../inputs/grep1.dat  > ../outputs/t653 2>&1

echo ">>>>>>>>running test 654"
../source/grep.exe "a[" ../inputs/grep1.dat  > ../outputs/t654 2>&1

echo ">>>>>>>>running test 655"
../source/grep.exe "a*[" ../inputs/grep1.dat  > ../outputs/t655 2>&1

echo ">>>>>>>>running test 656"
../source/grep.exe "[a" ../inputs/grep1.dat  > ../outputs/t656 2>&1

echo ">>>>>>>>running test 657"
../source/grep.exe "[1" ../inputs/grep1.dat  > ../outputs/t657 2>&1

echo ">>>>>>>>running test 658"
../source/grep.exe "[1-9" ../inputs/grep1.dat  > ../outputs/t658 2>&1

echo ">>>>>>>>running test 659"
../source/grep.exe "[1-]" ../inputs/grep1.dat  > ../outputs/t659 2>&1

echo ">>>>>>>>running test 660"
../source/grep.exe "[a-]" ../inputs/grep1.dat  > ../outputs/t660 2>&1

echo ">>>>>>>>running test 661"
../source/grep.exe "[1a-]" ../inputs/grep1.dat  > ../outputs/t661 2>&1

echo ">>>>>>>>running test 662"
../source/grep.exe "[[:alpha:]-5]" ../inputs/grep1.dat  > ../outputs/t662 2>&1

echo ">>>>>>>>running test 663"
../source/grep.exe "[z[:digit:]-f]" ../inputs/grep1.dat  > ../outputs/t663 2>&1

echo ">>>>>>>>running test 664"
../source/grep.exe "[[:alnum:]-9]" ../inputs/grep1.dat  > ../outputs/t664 2>&1

echo ">>>>>>>>running test 665"
../source/grep.exe "[1-2-9]" ../inputs/grep1.dat  > ../outputs/t665 2>&1

echo ">>>>>>>>running test 666"
../source/grep.exe "[a-c-z]" ../inputs/grep1.dat  > ../outputs/t666 2>&1

echo ">>>>>>>>running test 667"
../source/grep.exe "[1A-Z-A]" ../inputs/grep1.dat  > ../outputs/t667 2>&1

echo ">>>>>>>>running test 668"
../source/grep.exe "[[:digit:]-1-9]" ../inputs/grep1.dat  > ../outputs/t668 2>&1

echo ">>>>>>>>running test 669"
../source/grep.exe "[[:digit:]-A-Z]" ../inputs/grep1.dat  > ../outputs/t669 2>&1

echo ">>>>>>>>running test 670"
../source/grep.exe "[[:digit:]-a-z]" ../inputs/grep1.dat  > ../outputs/t670 2>&1

echo ">>>>>>>>running test 671"
../source/grep.exe "[1-2-" ../inputs/grep1.dat  > ../outputs/t671 2>&1

echo ">>>>>>>>running test 672"
../source/grep.exe "[1A-Z-" ../inputs/grep1.dat  > ../outputs/t672 2>&1

echo ">>>>>>>>running test 673"
../source/grep.exe "[Aa-z-" ../inputs/grep1.dat  > ../outputs/t673 2>&1

echo ">>>>>>>>running test 674"
../source/grep.exe "[1-" ../inputs/grep1.dat  > ../outputs/t674 2>&1

echo ">>>>>>>>running test 675"
../source/grep.exe "[1A-" ../inputs/grep1.dat  > ../outputs/t675 2>&1

echo ">>>>>>>>running test 676"
../source/grep.exe "[Aa-" ../inputs/grep1.dat  > ../outputs/t676 2>&1

echo ">>>>>>>>running test 677"
../source/grep.exe "[[:" ../inputs/grep1.dat  > ../outputs/t677 2>&1

echo ">>>>>>>>running test 678"
../source/grep.exe "a[[:" ../inputs/grep1.dat  > ../outputs/t678 2>&1

echo ">>>>>>>>running test 679"
../source/grep.exe "1-9[[:" ../inputs/grep1.dat  > ../outputs/t679 2>&1

echo ">>>>>>>>running test 680"
../source/grep.exe "[[:a:]]" ../inputs/grep1.dat  > ../outputs/t680 2>&1

echo ">>>>>>>>running test 681"
../source/grep.exe "[[:1:]]" ../inputs/grep1.dat  > ../outputs/t681 2>&1

echo ">>>>>>>>running test 682"
../source/grep.exe "[[:abcdefg:]]" ../inputs/grep1.dat  > ../outputs/t682 2>&1

echo ">>>>>>>>running test 683"
../source/grep.exe "[[:alpha:]" ../inputs/grep1.dat  > ../outputs/t683 2>&1

echo ">>>>>>>>running test 684"
../source/grep.exe "[a[:digit:]" ../inputs/grep1.dat  > ../outputs/t684 2>&1

echo ">>>>>>>>running test 685"
../source/grep.exe "[[:alnum:]" ../inputs/grep1.dat  > ../outputs/t685 2>&1

echo ">>>>>>>>running test 686"
../source/grep.exe "\ " ../inputs/grep1.dat  > ../outputs/t686 2>&1

echo ">>>>>>>>running test 687"
../source/grep.exe "if\ " ../inputs/grep1.dat  > ../outputs/t687 2>&1

echo ">>>>>>>>running test 688"
../source/grep.exe "else\ " ../inputs/grep1.dat  > ../outputs/t688 2>&1

echo ">>>>>>>>running test 689"
../source/grep.exe '\`' ../inputs/grep1.dat  > ../outputs/t689 2>&1

echo ">>>>>>>>running test 690"
../source/grep.exe 'if\`' ../inputs/grep1.dat  > ../outputs/t690 2>&1

echo ">>>>>>>>running test 691"
../source/grep.exe '\`else' ../inputs/grep1.dat  > ../outputs/t691 2>&1

echo ">>>>>>>>running test 692"
../source/grep.exe "\'" ../inputs/grep1.dat  > ../outputs/t692 2>&1

echo ">>>>>>>>running test 693"
../source/grep.exe "if\'" ../inputs/grep1.dat  > ../outputs/t693 2>&1

echo ">>>>>>>>running test 694"
../source/grep.exe "\'else" ../inputs/grep1.dat  > ../outputs/t694 2>&1

echo ">>>>>>>>running test 695"
../source/grep.exe "\1" ../inputs/grep1.dat  > ../outputs/t695 2>&1

echo ">>>>>>>>running test 696"
../source/grep.exe "\2" ../inputs/grep1.dat  > ../outputs/t696 2>&1

echo ">>>>>>>>running test 697"
../source/grep.exe "\3" ../inputs/grep1.dat  > ../outputs/t697 2>&1

echo ">>>>>>>>running test 698"
../source/grep.exe "\4" ../inputs/grep1.dat  > ../outputs/t698 2>&1

echo ">>>>>>>>running test 699"
../source/grep.exe "\5" ../inputs/grep1.dat  > ../outputs/t699 2>&1

echo ">>>>>>>>running test 700"
../source/grep.exe "\6" ../inputs/grep1.dat  > ../outputs/t700 2>&1

echo ">>>>>>>>running test 701"
../source/grep.exe "\7" ../inputs/grep1.dat  > ../outputs/t701 2>&1

echo ">>>>>>>>running test 702"
../source/grep.exe "\8" ../inputs/grep1.dat  > ../outputs/t702 2>&1

echo ">>>>>>>>running test 703"
../source/grep.exe "\9" ../inputs/grep1.dat  > ../outputs/t703 2>&1

echo ">>>>>>>>running test 704"
../source/grep.exe "\)" ../inputs/grep1.dat  > ../outputs/t704 2>&1

echo ">>>>>>>>running test 705"
../source/grep.exe "if\)" ../inputs/grep1.dat  > ../outputs/t705 2>&1

echo ">>>>>>>>running test 706"
../source/grep.exe "[a-z]\)" ../inputs/grep1.dat  > ../outputs/t706 2>&1

echo ">>>>>>>>running test 707"
../source/grep.exe "\{" ../inputs/grep1.dat  > ../outputs/t707 2>&1

echo ">>>>>>>>running test 708"
../source/grep.exe "a\{" ../inputs/grep1.dat  > ../outputs/t708 2>&1

echo ">>>>>>>>running test 709"
../source/grep.exe "[1-9]\{" ../inputs/grep1.dat  > ../outputs/t709 2>&1

echo ">>>>>>>>running test 710"
../source/grep.exe "\{2,1}" ../inputs/grep1.dat  > ../outputs/t710 2>&1

echo ">>>>>>>>running test 711"
../source/grep.exe "a\{2,1}" ../inputs/grep1.dat  > ../outputs/t711 2>&1

echo ">>>>>>>>running test 712"
../source/grep.exe "\{1" ../inputs/grep1.dat  > ../outputs/t712 2>&1

echo ">>>>>>>>running test 713"
../source/grep.exe "\{1,2" ../inputs/grep1.dat  > ../outputs/t713 2>&1

echo ">>>>>>>>running test 714"
../source/grep.exe "a\{1" ../inputs/grep1.dat  > ../outputs/t714 2>&1

echo ">>>>>>>>running test 715"
../source/grep.exe "\{1\{" ../inputs/grep1.dat  > ../outputs/t715 2>&1

echo ">>>>>>>>running test 716"
../source/grep.exe "\{1,2\{" ../inputs/grep1.dat  > ../outputs/t716 2>&1

echo ">>>>>>>>running test 717"
../source/grep.exe "[a-z]\{1,2\{" ../inputs/grep1.dat  > ../outputs/t717 2>&1

echo ">>>>>>>>running test 718"
../source/grep.exe "a\{1,2\}" ../inputs/grep1.dat  > ../outputs/t718 2>&1

echo ">>>>>>>>running test 719"
../source/grep.exe "[1-9]\{1,2\}" ../inputs/grep1.dat  > ../outputs/t719 2>&1

echo ">>>>>>>>running test 720"
../source/grep.exe "A\{1,2\}" ../inputs/grep1.dat  > ../outputs/t720 2>&1

echo ">>>>>>>>running test 721"
../source/grep.exe "A\{0\}" ../inputs/grep1.dat  > ../outputs/t721 2>&1

echo ">>>>>>>>running test 722"
../source/grep.exe "1\{0\}" ../inputs/grep1.dat  > ../outputs/t722 2>&1

echo ">>>>>>>>running test 723"
../source/grep.exe "[a-z]\{0\}" ../inputs/grep1.dat  > ../outputs/t723 2>&1

echo ">>>>>>>>running test 724"
../source/grep.exe "\(" ../inputs/grep1.dat  > ../outputs/t724 2>&1

echo ">>>>>>>>running test 725"
../source/grep.exe "a\(" ../inputs/grep1.dat  > ../outputs/t725 2>&1

echo ">>>>>>>>running test 726"
../source/grep.exe "a\(a" ../inputs/grep1.dat  > ../outputs/t726 2>&1

echo ">>>>>>>>running test 727"
../source/grep.exe "\|\(a\|b\)1*2\?3\+" ../inputs/grep1.dat  > ../outputs/t727 2>&1

echo ">>>>>>>>running test 728"
../source/grep.exe "\|\(if\|else\)1*2\?3\+" ../inputs/grep1.dat  > ../outputs/t728 2>&1

echo ">>>>>>>>running test 729"
../source/grep.exe "\|\(for\|12345\)a*b\?c\+" ../inputs/grep1.dat  > ../outputs/t729 2>&1

echo ">>>>>>>>running test 730"
../source/grep.exe "a" ../inputs/biginput.dat  > ../outputs/t730 2>&1

echo ">>>>>>>>running test 731"
../source/grep.exe "[a-z]" ../inputs/biginput.dat  > ../outputs/t731 2>&1

echo ">>>>>>>>running test 732"
../source/grep.exe "5\|7" ../inputs/biginput.dat  > ../outputs/t732 2>&1

echo ">>>>>>>>running test 733"
../source/grep.exe -5 if ../inputs/grep1.dat  > ../outputs/t733 2>&1

echo ">>>>>>>>running test 734"
../source/grep.exe -7 else ../inputs/grep1.dat  > ../outputs/t734 2>&1

echo ">>>>>>>>running test 735"
../source/grep.exe -4 12345 ../inputs/grep1.dat  > ../outputs/t735 2>&1

echo ">>>>>>>>running test 736"
../source/grep.exe "[[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t736 2>&1

echo ">>>>>>>>running test 737"
../source/grep.exe "1[[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t737 2>&1

echo ">>>>>>>>running test 738"
../source/grep.exe "a*[[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t738 2>&1

echo ">>>>>>>>running test 739"
../source/grep.exe -f ../inputs/biginput.dat ../inputs/grep1.dat  > ../outputs/t739 2>&1

echo ">>>>>>>>running test 740"
../source/grep.exe -f ../inputs/biginput2.dat ../inputs/grep1.dat  > ../outputs/t740 2>&1

echo ">>>>>>>>running test 741"
../source/grep.exe -f ../inputs/input_enter1 ../inputs/grep1.dat  > ../outputs/t741 2>&1

echo ">>>>>>>>running test 742"
../source/grep.exe -f ../inputs/input_enter2 ../inputs/grep1.dat  > ../outputs/t742 2>&1

echo ">>>>>>>>running test 743"
../source/grep.exe -f ../inputs/input_enter3 ../inputs/grep1.dat  > ../outputs/t743 2>&1

echo ">>>>>>>>running test 744"
../source/grep.exe "\\" ../inputs/grep1.dat  > ../outputs/t744 2>&1

echo ">>>>>>>>running test 745"
../source/grep.exe "1\\" ../inputs/grep1.dat  > ../outputs/t745 2>&1

echo ">>>>>>>>running test 746"
../source/grep.exe "a\\" ../inputs/grep1.dat  > ../outputs/t746 2>&1

echo ">>>>>>>>running test 747"
../source/grep.exe "\^" ../inputs/grep1.dat  > ../outputs/t747 2>&1

echo ">>>>>>>>running test 748"
../source/grep.exe "1\^" ../inputs/grep1.dat  > ../outputs/t748 2>&1

echo ">>>>>>>>running test 749"
../source/grep.exe "a\^" ../inputs/grep1.dat  > ../outputs/t749 2>&1

echo ">>>>>>>>running test 750"
../source/grep.exe "1\|^" ../inputs/grep1.dat  > ../outputs/t750 2>&1

echo ">>>>>>>>running test 751"
../source/grep.exe "a\|^" ../inputs/grep1.dat  > ../outputs/t751 2>&1

echo ">>>>>>>>running test 752"
../source/grep.exe "\(1\)^" ../inputs/grep1.dat  > ../outputs/t752 2>&1

echo ">>>>>>>>running test 753"
../source/grep.exe '\$' ../inputs/grep1.dat  > ../outputs/t753 2>&1

echo ">>>>>>>>running test 754"
../source/grep.exe 'if\$' ../inputs/grep1.dat  > ../outputs/t754 2>&1

echo ">>>>>>>>running test 755"
../source/grep.exe 'main\$' ../inputs/grep1.dat  > ../outputs/t755 2>&1

echo ">>>>>>>>running test 756"
../source/grep.exe '$' ../inputs/grep1.dat  > ../outputs/t756 2>&1

echo ">>>>>>>>running test 757"
../source/grep.exe 'if$' ../inputs/grep1.dat  > ../outputs/t757 2>&1

echo ">>>>>>>>running test 758"
../source/grep.exe 'main$' ../inputs/grep1.dat  > ../outputs/t758 2>&1

echo ">>>>>>>>running test 759"
../source/grep.exe '$if' ../inputs/grep1.dat  > ../outputs/t759 2>&1

echo ">>>>>>>>running test 760"
../source/grep.exe 'if$if' ../inputs/grep1.dat  > ../outputs/t760 2>&1

echo ">>>>>>>>running test 761"
../source/grep.exe 'if$else' ../inputs/grep1.dat  > ../outputs/t761 2>&1

echo ">>>>>>>>running test 762"
../source/grep.exe ">" ../inputs/grep1.dat  > ../outputs/t762 2>&1

echo ">>>>>>>>running test 763"
../source/grep.exe "1>" ../inputs/grep1.dat  > ../outputs/t763 2>&1

echo ">>>>>>>>running test 764"
../source/grep.exe "1>a" ../inputs/grep1.dat  > ../outputs/t764 2>&1

echo ">>>>>>>>running test 765"
../source/grep.exe "B" ../inputs/grep1.dat  > ../outputs/t765 2>&1

echo ">>>>>>>>running test 766"
../source/grep.exe "ABCDE" ../inputs/grep1.dat  > ../outputs/t766 2>&1

echo ">>>>>>>>running test 767"
../source/grep.exe "[A-B]" ../inputs/grep1.dat  > ../outputs/t767 2>&1

echo ">>>>>>>>running test 768"
../source/grep.exe "*" ../inputs/grep1.dat  > ../outputs/t768 2>&1

echo ">>>>>>>>running test 769"
../source/grep.exe "*a" ../inputs/grep1.dat  > ../outputs/t769 2>&1

echo ">>>>>>>>running test 770"
../source/grep.exe "*\(abcde\)" ../inputs/grep1.dat  > ../outputs/t770 2>&1

echo ">>>>>>>>running test 771"
../source/grep.exe "\+" ../inputs/grep1.dat  > ../outputs/t771 2>&1

echo ">>>>>>>>running test 772"
../source/grep.exe "1\+" ../inputs/grep1.dat  > ../outputs/t772 2>&1

echo ">>>>>>>>running test 773"
../source/grep.exe "if\+" ../inputs/grep1.dat  > ../outputs/t773 2>&1

echo ">>>>>>>>running test 774"
../source/grep.exe "+" ../inputs/grep1.dat  > ../outputs/t774 2>&1

echo ">>>>>>>>running test 775"
../source/grep.exe "+if" ../inputs/grep1.dat  > ../outputs/t775 2>&1

echo ">>>>>>>>running test 776"
../source/grep.exe "+else" ../inputs/grep1.dat  > ../outputs/t776 2>&1

echo ">>>>>>>>running test 777"
../source/grep.exe "{" ../inputs/grep1.dat  > ../outputs/t777 2>&1

echo ">>>>>>>>running test 778"
../source/grep.exe "if{" ../inputs/grep1.dat  > ../outputs/t778 2>&1

echo ">>>>>>>>running test 779"
../source/grep.exe "else{" ../inputs/grep1.dat  > ../outputs/t779 2>&1

echo ">>>>>>>>running test 780"
../source/grep.exe "1\{10,11\}2" ../inputs/grep1.dat  > ../outputs/t780 2>&1

echo ">>>>>>>>running test 781"
../source/grep.exe "a\{10,11\}b" ../inputs/grep1.dat  > ../outputs/t781 2>&1

echo ">>>>>>>>running test 782"
../source/grep.exe "if\{10,11\}else" ../inputs/grep1.dat  > ../outputs/t782 2>&1

echo ">>>>>>>>running test 783"
../source/grep.exe "\." ../inputs/grep1.dat  > ../outputs/t783 2>&1

echo ">>>>>>>>running test 784"
../source/grep.exe "1\.a" ../inputs/grep1.dat  > ../outputs/t784 2>&1

echo ">>>>>>>>running test 785"
../source/grep.exe "if\.else" ../inputs/grep1.dat  > ../outputs/t785 2>&1

echo ">>>>>>>>running test 786"
../source/grep.exe "\[" ../inputs/grep1.dat  > ../outputs/t786 2>&1

echo ">>>>>>>>running test 787"
../source/grep.exe "if\[" ../inputs/grep1.dat  > ../outputs/t787 2>&1

echo ">>>>>>>>running test 788"
../source/grep.exe "if\[else" ../inputs/grep1.dat  > ../outputs/t788 2>&1

echo ">>>>>>>>running test 789"
../source/grep.exe -i "[A-z1]" ../inputs/grep1.dat  > ../outputs/t789 2>&1

echo ">>>>>>>>running test 790"
../source/grep.exe -i "[C-x2]" ../inputs/grep1.dat  > ../outputs/t790 2>&1

echo ">>>>>>>>running test 791"
../source/grep.exe -i "if[Xx5]" ../inputs/grep1.dat  > ../outputs/t791 2>&1

echo ">>>>>>>>running test 792"
../source/grep.exe -X grep 12345 ../inputs/grep1.dat  > ../outputs/t792 2>&1

echo ">>>>>>>>running test 793"
../source/grep.exe -X grep abcde ../inputs/grep1.dat  > ../outputs/t793 2>&1

echo ">>>>>>>>running test 794"
../source/grep.exe -X grep if ../inputs/grep1.dat  > ../outputs/t794 2>&1

echo ">>>>>>>>running test 795"
../source/grep.exe -e 1 -e 2 ../inputs/grep1.dat  > ../outputs/t795 2>&1

echo ">>>>>>>>running test 796"
../source/grep.exe -e a -e b ../inputs/grep1.dat  > ../outputs/t796 2>&1

echo ">>>>>>>>running test 797"
../source/grep.exe -e if -e else ../inputs/grep1.dat  > ../outputs/t797 2>&1

echo ">>>>>>>>running test 798"
../source/grep.exe -e 12345 -e abcde -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t798 2>&1

echo ">>>>>>>>running test 799"
../source/grep.exe -e if -e else -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t799 2>&1

echo ">>>>>>>>running test 800"
../source/grep.exe -e 1 -e 2 -e 3 -e 4 -e 5 -e 12345 -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t800 2>&1

echo ">>>>>>>>running test 801"
../source/grep.exe -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t801 2>&1

echo ">>>>>>>>running test 802"
../source/grep.exe -i -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t802 2>&1

echo ">>>>>>>>running test 803"
../source/grep.exe -v -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t803 2>&1

echo ">>>>>>>>running test 804"
../source/grep.exe "\(\b\)*" ../inputs/grep1.dat  > ../outputs/t804 2>&1

echo ">>>>>>>>running test 805"
../source/grep.exe "if\(\b\)*" ../inputs/grep1.dat  > ../outputs/t805 2>&1

echo ">>>>>>>>running test 806"
../source/grep.exe "\(\b\)\+" ../inputs/grep1.dat  > ../outputs/t806 2>&1

echo ">>>>>>>>running test 807"
../source/grep.exe "\(\a|b*\|c\?|d\+\)\{1\}" ../inputs/grep1.dat  > ../outputs/t807 2>&1

echo ">>>>>>>>running test 808"
../source/grep.exe "\(\if|else*\|for\?|while\+\)\{1\}" ../inputs/grep1.dat  > ../outputs/t808 2>&1

echo ">>>>>>>>running test 809"
../source/grep.exe "\(\do|12345*\|main\?|A\+\)\{1\}" ../inputs/grep1.dat  > ../outputs/t809 2>&1

